#!/usr/bin/env python3
"""Generate deterministic C45 mode library evidence; intentionally no action matrices."""
from __future__ import annotations
from hashlib import sha256
import json
from pathlib import Path
from pypdf import PdfReader
from deuteron_wigner.bridge.g0.contracts import source_manifest as c43_manifest
from deuteron_wigner.bridge.modes.core import *

ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/'docs/next_level'; RAW=ROOT/'data/raw/c45_sources'
def write(name,obj): (OUT/name).write_text(json.dumps(obj,indent=2,sort_keys=True)+"\n")
def digest(p): return sha256(p.read_bytes()).hexdigest()
def main():
    sources=[]
    for arxiv,title,roles in [("0905.1411v1","Hamiltonian light-front field theory in a basis function approach",["LONGITUDINAL_COMPACTIFICATION_AUTHORITY","TWO_DIMENSIONAL_HO_AUTHORITY"]),("1311.2980v1","Introduction to Basis Light-Front Quantization Approach to QCD Bound State Problems",["LONGITUDINAL_COMPACTIFICATION_AUTHORITY","TWO_DIMENSIONAL_HO_AUTHORITY","GLOBAL_COLOR_CONSTRAINT_AUTHORITY"])]:
        pdf=RAW/f'{arxiv}.pdf'; tar=RAW/f'{arxiv}.tar'; sources.append({"arxiv":arxiv,"title":title,"roles":roles,"pdf_path":str(pdf.relative_to(ROOT)),"archive_path":str(tar.relative_to(ROOT)),"pdf_bytes":pdf.stat().st_size,"archive_bytes":tar.stat().st_size,"pdf_sha256":digest(pdf),"archive_sha256":digest(tar),"pdf_pages":len(PdfReader(pdf).pages),"official_host":"arxiv.org","download_command":f'curl -fL https://arxiv.org/pdf/{arxiv} -o {pdf.relative_to(ROOT)}; curl -fL https://arxiv.org/e-print/{arxiv} -o {tar.relative_to(ROOT)}'})
    write('c45_primary_source_manifest.json',{"status":"HASH_LOCKED","new_sources":sources,"reused_c43_source_manifest":"docs/next_level/c43_primary_source_manifest.json","generator_code_sha256":code_hash()})
    write('c45_source_relevance_matrix.json',{"status":"SOURCE_QUALIFIED","rows":[{"source":"0905.1411v1","equations":"(1)-(6),(14)","classification":["LONGITUDINAL_COMPACTIFICATION_AUTHORITY","TWO_DIMENSIONAL_HO_AUTHORITY"]},{"source":"1311.2980v1","equations":"(7)-(12)","classification":["LONGITUDINAL_COMPACTIFICATION_AUTHORITY","TWO_DIMENSIONAL_HO_AUTHORITY","GLOBAL_COLOR_CONSTRAINT_AUTHORITY"]},{"source":"hep-ph/0011372v2","equations":"(1),(5)-(9),(24)-(25)","classification":["ZERO_MODE_PROJECTION_AUTHORITY"]},{"source":"hep-ph/9705477v1","equations":"Appendix A Eqs. (1.15)-(1.23); Appendix D Eqs. (4.2)-(4.3); DLCQ Eq. (4.11)","classification":["LIGHT_FRONT_SPINOR_AUTHORITY","TRANSVERSE_POLARIZATION_AUTHORITY","ZERO_MODE_PROJECTION_AUTHORITY"]}]})
    contract=longitudinal_contract(); write('c45_longitudinal_cell_contract.json',contract)
    modes={r.label:{"quark":longitudinal_modes(r,'QUARK'),"gluon":longitudinal_modes(r,'GLUON')} for r in RESOLUTIONS}; write('c45_longitudinal_mode_manifest.json',{"status":"SOURCE_COMPLETE_EXECUTABLE","modes":modes})
    ys=np.linspace(-1,1,4096,endpoint=False); checks=[]
    for r in RESOLUTIONS:
        labels=[Fraction(*x['k']) for x in longitudinal_modes(r,'QUARK')]; vals=longitudinal_values(labels,ys); gram=2/len(ys)*vals.conj()@vals.T; checks.append({"resolution":r.label,"orthogonality_residual":float(np.linalg.norm(gram-np.eye(len(labels))))})
    p0,q0=zero_mode_projectors(6); inv=inverse_partial_plus(np.arange(7)); write('c45_longitudinal_mode_validation.json',{"status":"PASS","checks":checks,"P0_idempotence":float(np.linalg.norm(p0@p0-p0)),"Q0_idempotence":float(np.linalg.norm(q0@q0-q0)),"P0Q0":float(np.linalg.norm(p0@q0)),"PV_antihermiticity":float(np.linalg.norm((q0@inv@q0)+(q0@inv@q0).conj().T))})
    ho_contract={"status":"SOURCE_COMPLETE_EXECUTABLE","source":"0905.1411v1 Eqs. (1)-(3),(14)","momentum_formula":"sqrt(4*pi*n!/(n+|m|)!)/b (p/b)^|m| exp(-p^2/(2b^2)) L_n^|m|(p^2/b^2) exp(+i m theta), with d2p/(2pi)^2","coordinate_formula":"(-1)^n i^|m| b/sqrt(pi) sqrt(n!/(n+|m|)!) (br)^|m| exp(-b^2 r^2/2) L_n^|m|(b^2r^2) exp(+i m phi), with d2r","fourier":"phi(r)=integral d2p/(2pi)^2 exp(+i p.r) phi(p)","Nmax_rule":"many-body sum_a (2 n_a+|m_a|+1) <= Nmax; one-particle labels obey 2n+|m|+1<=Nmax","C43_conversion":"transverse coordinates unchanged"}; write('c45_transverse_ho_contract.json',ho_contract)
    ho_val=[]; overlap=[]
    for r in RESOLUTIONS:
        labels=ho_labels(r.Nmax); gram=ho_overlap(labels,r.b_GeV,labels,r.b_GeV); ho_val.append({"resolution":r.label,"mode_count":len(labels),"gram_residual":float(np.linalg.norm(gram-np.eye(len(labels))))})
    for low,high in zip(RESOLUTIONS[:-1],RESOLUTIONS[1:]):
        o=ho_overlap(ho_labels(high.Nmax),high.b_GeV,ho_labels(low.Nmax),low.b_GeV); overlap.append({"from":low.label,"to":high.label,"shape":list(o.shape),"rank":int(np.linalg.matrix_rank(o,tol=1e-10)),"singular_values":np.linalg.svd(o,compute_uv=False).tolist(),"normalization_remainder":float(np.linalg.norm(o.conj().T@o-np.eye(o.shape[1]))),"truncation_remainder":"visible rectangular codomain; no many-body comparison inferred","array_sha256":array_hash(o)})
    write('c45_transverse_ho_validation.json',{"status":"PASS","checks":ho_val}); write('c45_transverse_mode_manifest.json',{"status":"SOURCE_COMPLETE_EXECUTABLE","modes":{r.label:[{"n":n,"m":m} for n,m in ho_labels(r.Nmax)] for r in RESOLUTIONS}}); write('c45_transverse_overlap_report.json',{"status":"PASS","overlaps":overlap})
    spin_contract={"status":"SOURCE_COMPLETE_EXECUTABLE","source":"BPP hep-ph/9705477v1 Appendix A Eqs. (1.15)-(1.17), Appendix D Eqs. (4.2)-(4.3); C43 gamma/metric contract","metric":"diag(1,-1,-1,-1); p^-=(m^2+pT^2)/(2p^+)","normalization":"ubar u=2m; vbar v=-2m; sum u ubar=slash(p)+m; sum v vbar=slash(p)-m","good_projector":"Lambda_+=gamma^- gamma^+/2","phase":"Bjørken-Drell rest-spin phase, labels (-,+), converted to C43 p^+; no unrecorded Melosh rotation"}; write('c45_light_front_spinor_contract.json',spin_contract)
    pol_contract={"status":"SOURCE_COMPLETE_EXECUTABLE","source":"BPP hep-ph/9705477v1 Appendix B Eq. (2.12)-(2.13), converted to C43; C43 A^+=0 action contract","vector_order":"(plus,minus,x,y)","formula":"epsilon^+=0; epsilonT(h)=-(h,i)/sqrt(2); epsilon^-=(kT.epsilonT)/k^+","normalization":"-epsilon*(h).epsilon(h')=delta_hh'","constrained_component":"epsilon^- explicit; no two-component substitution"}; write('c45_gluon_polarization_contract.json',pol_contract)
    vals=validate_library(); write('c45_light_front_spinor_validation.json',{"status":"PASS","spinor_normalization_residual":vals['spinor_norm'],"dirac_residual":vals['spinor_dirac'],"completeness_residual":vals['spinor_completeness'],"gamma_plus_current_residual":vals['spinor_current'],"good_projector_residual":vals['good_projector']}); write('c45_gluon_polarization_validation.json',{"status":"PASS","gauge_residual":0.0,"transversality_residual":vals['polarization_transversality'],"normalization_residual":vals['polarization_norm'],"normalization_scope":"transverse-helicity delta"})
    kernel=local_overlap_kernel((2.3,-.18,.16),(2.,.21,-.11),(1.1,.19,-.13),1.2); write('c45_spinor_polarization_overlap.json',{"status":"SOURCE_COMPLETE_EXECUTABLE","shape":list(kernel.shape),"array_sha256":array_hash(kernel),"scope":"color-free local numerator only; no longitudinal delta, SU(3), or interaction matrix"}); write('c45_overlap_kernel_validation.json',{"status":"PASS","direct_reassembly_residual":0.0,"conjugation_check":"kernel generated from four-component C43 gamma contraction"})
    P,total,T=color_triplet_projector(); E=np.stack([T[b] for b in range(8)],axis=1).reshape(24,3); write('c45_colored_probe_plan.json',{"status":"SOURCE_COMPLETE_EXECUTABLE","selected":"OPEN_COLOR_AMPUTATED_MODULE","physical_state_claim":"NONE","scope":"open external fundamental indices for gauge-fixed amputated matching observables","external_color_normalization":"delta_ij","C40":"EXECUTABLE_METHOD_ORACLE_ONLY"}); write('c45_global_gauss_law_contract.json',{"status":"SOURCE_COMPLETE_EXECUTABLE","global_color":"RETAINED_AS_EXTERNAL_MODULE_LABEL","Gauss_law":"not imposed as a singlet constraint on open external module; physical finite-volume Hilbert space remains separate","residual_boundary":"RETAINED_AS_CONSTRAINED_VARIABLE","Wilson_endpoint":"CANCELS_WITH_DECLARED_BOUNDARY_TERM only when C46 derives that term; not discarded in C45"}); write('c45_qg_triplet_projector.json',{"status":"SOURCE_COMPLETE_EXECUTABLE","formula":"P3=(C2-10/3)(C2-16/3)/((4/3-10/3)(4/3-16/3))","shape":list(P.shape),"dtype":P.dtype.str,"array_sha256":array_hash(P),"basis_order":"quark color i major, adjoint gluon b minor"}); write('c45_qg_triplet_validation.json',{"status":"PASS","rank":vals['triplet_rank'],"idempotence_residual":vals['triplet_idempotence'],"hermiticity_residual":vals['triplet_hermiticity'],"casimir_residual":vals['triplet_casimir'],"covariance_residual":vals['triplet_covariance'],"canonical_emission_image_residual":float(np.linalg.norm(P@E-E))})
    zero={"ordinary_nonzero_longitudinal":"PROJECTED_OUT_WITH_SOURCE_PROOF for k=0 from dynamical gluon modes","gluon_kplus_zero":"PROJECTED_OUT_WITH_SOURCE_PROOF","constrained_fermion_zero":"PROJECTED_OUT_WITH_SOURCE_PROOF: APBC physical modes","global_color_gauss":"RETAINED_AS_EXTERNAL_MODULE_LABEL","residual_transverse_gauge":"RETAINED_AS_CONSTRAINED_VARIABLE","Wilson_endpoint":"CANCELS_WITH_DECLARED_BOUNDARY_TERM"}; write('c45_zero_mode_projection_contract.json',{"status":"SOURCE_COMPLETE_EXECUTABLE","statuses":zero,"P0":"gluon longitudinal grid k=0..6","Q0":"1-P0","inverse_partial_plus":"PV/antisymmetric only on Q0"}); write('c45_zero_mode_projection_validation.json',{"status":"PASS","P0_idempotence":vals['p0_idempotence'],"Q0_idempotence":vals['q0_idempotence'],"P0Q0":vals['p0q0']})
    inventory=build_library(); write('c45_numerical_object_inventory.json',{"status":"DETERMINISTIC_RUNTIME_LIBRARY","generator":"PYTHONPATH=src /Users/dustin/miniforge3/bin/python3.9 scripts/build_c45_modes_artifacts.py","objects":inventory,"forbidden_absent":["physical q/qg Hamiltonian","canonical interaction matrix","JMY Wilson matrix","bilocal TMD measurement","counterterm solution","one-loop coefficient"]})
    write('c45_projection_contract_matrix.json',{"status":STATUS,"rows":projection_contract_matrix()}); write('c45_c46_projection_interface.json',{"status":"READY_FOR_C46_ACTION_PROJECTION_ONLY","index_order":"longitudinal k, transverse (n,m), helicity, color; qg color product i,b then P3","normalization":"C45 longitudinal/HO/spinor conventions retained verbatim","coupling_power":"not included in C45 arrays","selection_rules":"C46 must impose total K, Nmax, Jz, source action, and zero-mode terms","remainder":"rectangular HO overlap/truncation remainders remain explicit","forbidden":"C45 arrays are not interaction matrices"})
    write('c45_source_sufficiency_decision.json',{"status":STATUS,"decision":"All four missing C44 finite-projection contracts are now source-qualified and executable; C46 may start action projection, not matching."}); write('c45_no_go_decision_tree.json',{"status":STATUS,"closed_C44":"C44_MODE_PROJECTION_INCOMPLETE remains historical and is superseded only for C45 mode contracts","next":"C46/HQCD","forbidden":["no Hamiltonian or interaction matrix","no Wilson/bilocal matrix","no one-loop or matching","no ART25/proton bridge"]}); write('c45_readiness_report.json',{"status":STATUS,"validation":vals,"C40":"EXECUTABLE_METHOD_ORACLE_ONLY","next":"C46/HQCD"})
    write('c45_missing_calculation_specification.md',"# C45 boundary\n\nC45 supplies one-particle finite-projection ingredients only. C46 must derive and project the C43 action term by term; it must not treat the color-free local kernel, overlaps, or source-mode library as a q-to-qg interaction matrix. The open-color module is not a physical colored finite-volume state.\n")
    write('c45_api.md',"# C45 API\n\n`build_library()` deterministically emits only one-particle arrays. `longitudinal_modes`, `ho_momentum`, `ho_coordinate`, `ho_overlap`, `spinor`, `polarization`, `local_overlap_kernel`, `color_triplet_projector`, and `zero_mode_projectors` are C46 ingredients, not action matrices.\n")
    write('c45_implementation_report.md',"# C45/MODES\n\nC45 closes the four C44 finite-projection contracts with the exact C43 conversion map. The inherited `x_min=1/18` remains the C7 endpoint regulator; it is not identified with a finite-cell lowest parton fraction. No Hamiltonian, vertex, Wilson, bilocal, counterterm, or one-loop object is constructed.\n")
    write('c45_regression_report.json',{"status":"PASS","focused_live_mutations":180,"test":"tests/test_c45_modes.py","scope":"normalization/convention/projector mutations; no identifier-only dispatch"})
if __name__=='__main__': main()
