"""Typed eikonal-phase construction for T-odd nucleon TMD boundaries.

This is an amplitude-level *model* interface.  It is deliberately distinct
from a fitted momentum-space TMD: the imaginary interference is generated
from a real reference amplitude and an operator/flavor-specific eikonal
phase.  Reversing a simple future/past staple conjugates that phase and hence
reverses the T-odd interference. Mixed links require their own calculation.
"""

from __future__ import annotations

from dataclasses import dataclass
import math
from typing import Callable, Mapping

from .gtmd import GaugeLink
from .nucleon_inputs import FittedMomentumTMDInput, ISOSPIN_ROTATION
from .provenance import ComponentProvenance, EvidenceClass, Mechanism, ValidityDomain

Amplitude = Callable[[str, int, float, float, float], float]
Phase = Callable[[str, int, float, float, float], float]

T_ODD_QUARK_OPERATORS = ("f1Tperp", "h1perp")


def simple_staple_orientation(gauge_link: GaugeLink) -> float:
    """Return +1 for future and -1 for past staples; refuse mixed links."""

    if gauge_link.incoming == gauge_link.outgoing == "+":
        return 1.0
    if gauge_link.incoming == gauge_link.outgoing == "-":
        return -1.0
    raise ValueError("mixed gauge links require an explicit process calculation")


@dataclass(frozen=True)
class QuarkEikonalPhaseModel:
    """Operator- and flavor-resolved imaginary interference model.

    For each operator, the reference amplitude ``A`` and phase ``chi`` define

    ``F_Todd = 2 A^2 sin(chi)``.

    This is the exact interference generated by amplitudes
    ``A`` and ``i A exp(i chi)`` in the chosen normalization.  It is a useful
    replaceable construction, not a derivation of the Wilson line from QCD.
    """

    reference_amplitudes: Mapping[str, Amplitude]
    phases: Mapping[str, Phase]
    source: str
    validity: ValidityDomain
    uncertainty_kind: str

    def __post_init__(self) -> None:
        expected = set(T_ODD_QUARK_OPERATORS)
        if set(self.reference_amplitudes) != expected or set(self.phases) != expected:
            raise ValueError("independent Sivers and Boer--Mulders amplitudes/phases required")
        if not self.source or not self.uncertainty_kind:
            raise ValueError("phase model requires source and uncertainty description")

    def future_value(
        self,
        operator: str,
        nucleon: str,
        flavor: int,
        x: float,
        k_gev: float,
        q_gev: float,
    ) -> float:
        if operator not in T_ODD_QUARK_OPERATORS:
            raise KeyError(f"unsupported T-odd operator {operator}")
        if not self.validity.contains(x=x, q_gev=q_gev, k_gev=k_gev):
            return 0.0
        amplitude = float(
            self.reference_amplitudes[operator](nucleon, flavor, x, k_gev, q_gev)
        )
        phase = float(self.phases[operator](nucleon, flavor, x, k_gev, q_gev))
        if not math.isfinite(amplitude) or not math.isfinite(phase):
            raise ValueError("eikonal amplitude and phase must be finite")
        return float(2.0 * amplitude**2 * math.sin(phase))

    def fitted_input(self, operator: str) -> FittedMomentumTMDInput:
        """Adapt one modeled future-staple interference to the nucleon layer."""

        if operator not in T_ODD_QUARK_OPERATORS:
            raise KeyError(f"unsupported T-odd operator {operator}")

        def response(
            nucleon: str, flavor: int, x: float, k: float, q: float
        ) -> float:
            return self.future_value(operator, nucleon, flavor, x, k, q)

        return FittedMomentumTMDInput(
            response=response,
            provenance=ComponentProvenance(
                name=f"modeled eikonal phase for {operator}",
                evidence=EvidenceClass.MODEL,
                mechanism=Mechanism.NUCLEON_IMPULSE,
                sources=(self.source,),
                assumptions=(
                    "future-pointing staple is the reference",
                    "T-odd term is an amplitude-level imaginary interference",
                    "Sivers and Boer--Mulders use independent amplitudes and phases",
                    "mixed links are outside this model",
                ),
                validity=self.validity,
                uncertainty_kind=self.uncertainty_kind,
                replaceable_interface="QuarkEikonalPhaseModel",
            ),
            process_reference="SIDIS future-pointing gauge link",
        )

    def neutron_from_proton_phase(
        self, operator: str, flavor: int, x: float, k_gev: float, q_gev: float
    ) -> float:
        """Diagnostic exact-CS rotation without an early isoscalar sum."""

        return self.future_value(
            operator,
            "proton",
            ISOSPIN_ROTATION.get(flavor, flavor),
            x,
            k_gev,
            q_gev,
        )
