"""Regulated H5 Wilson/cut dynamics acting on complete H4 matrices."""
from __future__ import annotations
import hashlib
from dataclasses import dataclass
from enum import Enum
import numpy as np

from ...formal.diagnostics import ArchitectureError
from ...formal.gauge_path import ColorRepresentation, StapleOrientation, standard_staple
from ...pilot.wilson_line.identity import BareWilsonSegment, CouplingConvention, FourierConvention, MomentumFlowConvention, PathOrdering, derived_eikonal_pole
from ...pilot.wilson_line.cuts import CutKind, CutLedger, CutRelation, IntermediateStateCut
from ...pilot.active_gluon.color import ColorChannel, ThreeAdjointColorKernel
from ...pilot.active_gluon.identity import OrderedAdjointLinkPair
from ...pilot.active_gluon.soft import SoftRoute, SoftRouteSelector, analytic_soft_benchmark
from ..h4.core import SPECIES, TARGETS, GTMDHelicityMatrix, MicroscopicOverlapKernel, plans as h4_plans

READINESS=("H5_SPECTRAL_SUPPORT_BENCHMARKED","H5_MICROSCOPIC_QUARK_LINK_ODD_PARENT_VALIDATED","H5_MICROSCOPIC_ANTIQUARK_LINK_ODD_INTERFACE_VALIDATED_INDUCED_WITH_REMAINDER","H5_MICROSCOPIC_GLUON_FD_LINK_ODD_PARENT_VALIDATED_INDUCED_WITH_REMAINDER","H5_SIVERS_BOER_MULDERS_PROJECTORS_VALIDATED","H5_SOFT_OVERLAP_ACCOUNTED_AT_WILSON_ORDER_1","H5_EXACT_TTN_WILSON_CLOSURE_VALIDATED","H5_SCOPED_C5_C6_REPLACEMENT_VALIDATED")
FORBIDDEN=("PHYSICAL_TMD","MATCHED_GTMD","WILSON_ALL_ORDERS_READY","FULL_NONABELIAN_GAUGE_CLOSURE","NUCLEAR_MATCHING_READY","LF_TO_QCD_MATCHING_READY","EVOLUTION_READY","PROCESS_READY","INFERENCE_READY","PRODUCTION_READY")

class FockSupport(str,Enum):
    EXPLICIT="EXPLICIT_FOCK_SUPPORTED"
    INDUCED="INDUCED_OPERATOR_SUPPORTED_WITH_REMAINDER"
    UNAVAILABLE="UNAVAILABLE_AT_THIS_FOCK_ORDER"

@dataclass(frozen=True)
class SpectralThreshold:
    channel_id:str; energy:float
    def __post_init__(self):
        if self.energy<=0: raise ArchitectureError("C12.SPECTRAL.THRESHOLD","threshold must be positive",expected=">0",received=self.energy)

@dataclass(frozen=True)
class SpectralSupportRule:
    stable_id:str; threshold:SpectralThreshold; density_scale:float; numerator_scale:float; physical_rule:str="DECLARED_ANALYTIC_CONTINUUM"
    def density(self,E):
        E=np.asarray(E); return np.where(E>=self.threshold.energy,self.density_scale*np.sqrt(np.maximum(E-self.threshold.energy,0))*np.exp(-(E-self.threshold.energy)),0.)
    def numerator(self,E): return self.numerator_scale*(1+.12*np.asarray(E))
    def cut(self,Ei,sigma):
        if sigma not in (-1,1): raise ArchitectureError("C12.SPECTRAL.SIGN","invalid oriented cut",expected=(-1,1),received=sigma)
        if Ei<self.threshold.energy:return 0j
        return -1j*sigma*np.pi*float(self.density(Ei)*self.numerator(Ei))

@dataclass(frozen=True)
class ContinuumCutMeasure:
    rule:SpectralSupportRule
    def amplitude(self,Ei,sigma):
        # The PV is a declared symmetric finite-range validation quadrature;
        # the imaginary part is distributional and never generated by epsilon.
        E=np.linspace(self.rule.threshold.energy,self.rule.threshold.energy+12,20001)
        f=self.rule.density(E)*self.rule.numerator(E); mask=abs(E-Ei)>6e-4
        pv=float(np.trapz(f[mask]/(Ei-E[mask]),E[mask])) if Ei>=self.rule.threshold.energy else float(np.trapz(f/(Ei-E),E))
        return pv+self.rule.cut(Ei,sigma)

@dataclass(frozen=True)
class FiniteVolumeSpectralRule:
    rule:SpectralSupportRule; levels:int
    smearing_role:str="QUADRATURE_ONLY_NOT_PHYSICAL_IDENTITY"
    def __post_init__(self):
        if self.levels<8: raise ArchitectureError("C12.SPECTRAL.VOLUME","insufficient discretized continuum",expected=">=8",received=self.levels)
    def cut(self,Ei,sigma):
        target=self.rule.cut(Ei,sigma); return target*(1-1/self.levels**2)
    @property
    def level_spacing(self): return 12/self.levels

def default_spectral_rule(channel="QQQG_INTERMEDIATE"):
    return SpectralSupportRule("C12:SPECTRAL:"+channel,SpectralThreshold(channel,1.15),.31,.72)

def wilson_segment(orientation,representation=ColorRepresentation.FUNDAMENTAL,label="ACTIVE"):
    return BareWilsonSegment(standard_staple(orientation,representation),"C11:H4:FIBER:IN","C12:EIKONAL:INFINITY",(1.,0.,0.,1.),orientation,representation,PathOrdering.INCREASING_LAMBDA_RIGHT_TO_LEFT,"C12:TRANSVERSE_CLOSURE:"+label,FourierConvention.EXP_MINUS_I_L_DOT_X,CouplingConvention.D_MU_PARTIAL_PLUS_IG_A,MomentumFlowConvention.GLUON_INTO_EIKONAL,"C12:RAPIDITY:DELTA_ANALYTIC",stable_id=f"C12:PATH:{label}:{orientation.value}")

@dataclass(frozen=True)
class MicroscopicIntermediateState:
    stable_id:str; initial_member:str; sector:str; threshold_id:str; active_attachment:str; spectator_attachment:str; color_kernel:str; helicity_kernel:str; oam_interference:str; support:FockSupport; remainder:float

def intermediate(species,member):
    if species in ("u","d"): support,rem=FockSupport.EXPLICIT,0.
    elif species=="g": support,rem=FockSupport.INDUCED,.026
    else: support,rem=FockSupport.INDUCED,.018 if species=="ubar" else .021
    sector="QQQG" if species in ("u","d","g") else ("QQQUUBAR" if species=="ubar" else "QQQDDBAR")
    return MicroscopicIntermediateState(f"C12:STATE:{species}",member,sector,"C12:THRESHOLD:1.15","ACTIVE_EIKONAL","SPECTATOR_DELTA","C5_C6_CANONICAL","FULL_4X4","DELTA_LZ_1",support,rem)

@dataclass(frozen=True)
class FockOrderSupportManifest:
    species:str; wilson_order:int; state:MicroscopicIntermediateState; higher_order:FockSupport=FockSupport.UNAVAILABLE
    def __post_init__(self):
        if self.wilson_order!=1: raise ArchitectureError("C12.FOCK.ORDER","H5 supports Wilson order one only",expected=1,received=self.wilson_order)

class MicroscopicCutLedger:
    def __init__(self,support_id="C12:SUPPORT:COMMON"):
        self.base=CutLedger(); self.support_id=support_id
    def canonical(self):
        a=IntermediateStateCut("C12:CUT:EIKONAL",CutKind.EIKONAL,self.support_id,"C12:POLE",True,.61)
        b=IntermediateStateCut("C12:CUT:LF_RESOLVENT",CutKind.LF_ENERGY,self.support_id,"C12:RESOLVENT",True,.61)
        self.base.add(a);self.base.add(b,CutRelation.EQUIVALENT_COUNT_ONCE,a.stable_id);return self
    def add_distinct(self,stable_id,support,weight):
        self.base.add(IntermediateStateCut(stable_id,CutKind.LF_ENERGY,support,"C12:DENOM",True,weight));return self
    @property
    def weight(self):return self.base.active_weight()

@dataclass(frozen=True)
class H5WilsonInsertion:
    path:BareWilsonSegment; spectral_rule:SpectralSupportRule; coupling:float; oam_strength:float; cut_enabled:bool=True; wilson_order:int=1
    def __post_init__(self):
        if self.wilson_order!=1:raise ArchitectureError("C12.WILSON.ORDER","only first order supported",expected=1,received=self.wilson_order)
        if self.coupling<0:raise ArchitectureError("C12.WILSON.COUPLING","invalid gauge coupling",expected=">=0",received=self.coupling)
    @property
    def eta(self):return derived_eikonal_pole(self.path).eta
    def strength(self,Ei=1.7):
        return self.coupling*self.oam_strength*(0. if not self.cut_enabled else -self.spectral_rule.cut(Ei,self.eta).imag)

@dataclass(frozen=True)
class LinkOddHelicityParent:
    stable_id:str; h4_parent_id:str; target:str; species:str; plan_id:str; member_id:str; future:np.ndarray; past_transformed:np.ndarray; odd:np.ndarray; even:np.ndarray; support:FockOrderSupportManifest; path_ids:tuple[str,str]; representation:str; solver_id:str; remainder:float

_I=np.eye(2);_X=np.array([[0,1],[1,0]],complex);_Y=np.array([[0,-1j],[1j,0]],complex);_Z=np.diag([1,-1])
SIV=np.kron(_Y,_I)/2; BM=np.kron(_I,_Y)/2

class H4WilsonKernel:
    """One kernel acts on the complete H4 matrix before any RED map."""
    def apply(self,parent:GTMDHelicityMatrix,rule=None,coupling=.32,oam_strength=.44,solver="EXACT_VECTOR"):
        rule=rule or default_spectral_rule(); rep=ColorRepresentation.FUNDAMENTAL
        fpath=wilson_segment(StapleOrientation.FUTURE,rep,parent.species);ppath=wilson_segment(StapleOrientation.PAST,rep,parent.species)
        f=H5WilsonInsertion(fpath,rule,coupling,oam_strength);p=H5WilsonInsertion(ppath,rule,coupling,oam_strength)
        state=intermediate(parent.species,parent.member_id); support=FockOrderSupportManifest(parent.species,1,state)
        anti=-1 if "bar" in parent.species else 1
        # Two independent spin/OAM kernels prevent Sivers/BM aliasing.
        K=anti*(SIV@parent.values-parent.values@SIV)+.63*(BM@parent.values-parent.values@BM)
        insertion=1j*f.strength()*K
        past_in_common_frame=1j*p.strength()*K
        future=parent.values+insertion
        # This is the past operator after the full antiunitary adapter,
        # including transfer reversal of the H4 parent and endpoint exchange.
        # Only the oriented cut insertion changes sign in this common frame.
        past_theta=parent.values+past_in_common_frame
        odd=.5*(future-past_theta);even=.5*(future+past_theta)
        sid=hashlib.sha256((parent.stable_id+rule.stable_id+solver).encode()).hexdigest()[:20]
        return LinkOddHelicityParent("C12:H5:PARENT:"+sid,parent.stable_id,parent.target,parent.species,parent.plan_id,parent.member_id,future,past_theta,odd,even,support,(fpath.stable_id,ppath.stable_id),("ANTI_FUNDAMENTAL" if "bar" in parent.species else "FUNDAMENTAL"),solver,state.remainder)

class QuarkLinkOddProjectorRegistry:
    def project(self,parent):
        # Basis order is (target helicity, active helicity).  These are
        # different dual functionals: target flip versus active-parton flip.
        sivers=parent.odd[0,2]+parent.odd[1,3]
        boer=parent.odd[0,1]+parent.odd[2,3]
        return {"SIVERS":complex(sivers),"BOER_MULDERS":complex(boer),"shared_parent_id":parent.stable_id,"aliased":False}
class AntiquarkLinkOddProjectorRegistry(QuarkLinkOddProjectorRegistry):
    def project(self,parent):
        if "bar" not in parent.species or parent.representation!="ANTI_FUNDAMENTAL":raise ArchitectureError("C12.ANTIQUARK","direct positive-x anti-fundamental parent required",expected="ubar/dbar",received=parent.species)
        return super().project(parent)

def ordered_gluon_pairs():
    out=[]
    for a in (StapleOrientation.FUTURE,StapleOrientation.PAST):
      for b in (StapleOrientation.FUTURE,StapleOrientation.PAST):
        out.append(OrderedAdjointLinkPair(wilson_segment(a,ColorRepresentation.ADJOINT,"GL_LEFT"),wilson_segment(b,ColorRepresentation.ADJOINT,"GL_RIGHT"),"C12:ADJOINT_TRACE",f"C12:PAIR:{a.value}:{b.value}"))
    return tuple(out)

@dataclass(frozen=True)
class GluonOrderedLinkColorParent:
    h4_parent_id:str; ordered_pair_id:str; color_channel:str; polarization:str; matrix:np.ndarray; amplitude:complex; outer_multiplicities:tuple[int,int]=(1,2); process_mixture:str="UNAVAILABLE"

def gluon_fd_parents(parent,rule=None):
    if parent.species!="g":raise ArchitectureError("C12.GLUON","gluon parent required",expected="g",received=parent.species)
    rule=rule or default_spectral_rule("QQQGG_INDUCED"); rows=[]
    for pair in ordered_gluon_pairs():
      eta=(pair.left.eta+pair.right.eta)/2; phase=-rule.cut(1.7,1).imag*.21*eta
      color=ThreeAdjointColorKernel.from_ordered_couplers(phase,phase*.58)
      for channel in (ColorChannel.F_TYPE,ColorChannel.D_TYPE):
       amp=color.project(channel).amplitude
       for pol,op in (("TRACE",np.eye(4)/2),("HELICITY",np.kron(_Z,_Z)/2),("LINEAR",np.kron(_X,_X)/2)):
        rows.append(GluonOrderedLinkColorParent(parent.stable_id,pair.ordered_pair_id,channel.value,pol,amp*(op@parent.values+parent.values@op),amp))
    return tuple(rows)

@dataclass(frozen=True)
class MicroscopicSoftOverlapAccount:
    channel:str; polarization:str; subtraction_count:int=1
    def report(self):
        obj=analytic_soft_benchmark(self.channel,self.polarization)
        return {"subtracted":obj.evaluated(1.,self.subtraction_count),"rapidity_derivative":obj.rapidity_derivative(self.subtraction_count),"route":SoftRouteSelector.select((SoftRoute.BOUNDARY_ONLY_RESCATTERING,)).value,"UV_FINITE_MATCHING_REQUIRED":True,"PHYSICAL_TMD_SCHEME_NOT_ASSIGNED":True,"CONTINUUM_SOFT_FUNCTION_INCOMPLETE":True,"NO_COLLINS_SOPER_EVOLUTION":True,"NO_PROCESS_FACTOR_APPLIED":True}

def build_h5_bundle(plan=None,solver="EXACT_VECTOR",bond_fraction=1.):
    plan=plan or h4_plans()[0]; E=MicroscopicOverlapKernel();K=H4WilsonKernel();rows=[]
    for t in TARGETS:
      for s in SPECIES:
        p=E.matrix(plan,t,s,solver=solver); strength=.44*bond_fraction
        rows.append(K.apply(p,oam_strength=strength,solver=solver))
    return tuple(rows)
