"""Nullspace-safe symbolic reduced map over the C136 identifiable quotient."""
from __future__ import annotations
import json
from hashlib import sha256
from pathlib import Path
from types import MappingProxyType
from typing import Any

ROOT=Path(__file__).resolve().parents[4]; RUNTIME=ROOT/"data/runtime/c137_hqcdrenred"
BASELINE="322671771f1e8eee040bb92d9f427442d642bae8"; CONTRACT="docs/next_level/c136_c137_hqcdrenred_import_contract.json"
STATUS="C137_C136_CONDITIONAL_REDUCED_HQCD_RENORMALIZATION_MAP_READY"; NEXT="C138/HQCDINPUT3"; SCHEMA="C137-HQCDRENRED-V1"
C136_ROOT="fac2b3210bfef7cd3dc22a1a05ea47d9253a641172308603f4c2f3b6c31eb262"; C135_ROOT="e94b1bb47b0ab2d7499922ef558a8b32f0c6796ee7edcf2d86aed9e048ddcb5b"; C134_ROOT="709a8955c466cee493da30fe23b9a31b85d63e8541e256ba92f6ce21568a9dd4"; C133_ROOT="c47a70ad4a87cac048db0c00fd1e24e7f5bde110596aec9116bcfc34bde9add9"; C132_ROOT="192de102695f89ed00aa1a1f1959395c28118177bb59b9ae9c4ec11ecaf84adc"; C131_ROOT="67ab09bdc4ef7960a7d39ee35c243cec5c6537087012ea6283d5b4da8259cbd4"; C130_ROOT="d674025fff1839ea53115b85a32b8780bac567691d143c303dddcf33ef0b2dbe"; C129_ROOT="4c85424eb7cfa6a6ee190e907c36245ca0325623e4de79e923007583a9804678"; C128_ROOT="d23ce7d398204f1e88612448564d26d17019fa832c8c041d3382c7be1553a6f1"; C127_ROOT="0615f7b5c25f30f91501e250f7a2c72bf242077dfe562d42abf259012a8ed11f"; C126_ROOT="84bec93a7598129f1cca71f5289d5e8a196cbc09897708d0527b746a3db6ad84"; C125_ROOT="a66760cec74797e7295cdf2983d2d40d7782d0fe909b5f57558401276cfcc9df"
DIRECTIONS=("m_q","m_q^2","g_s","ct_mass","ct_vacuum_energy","ct_gluon_mass","ct_sector","ct_boundary","ct_truncation","vacuum_direction_coefficient","truncation_direction_coefficient")
RESOLUTIONS=("K9_2_N8_b0.40","K11_2_N10_b0.45","K13_2_N12_b0.50")
SELECTED=("C136_MASS_K9","C136_VERTEX_LONGITUDINAL")
def _plain(x:Any)->Any:
    if isinstance(x,MappingProxyType):return {k:_plain(v) for k,v in x.items()}
    if isinstance(x,(tuple,list)):return [_plain(v) for v in x]
    if isinstance(x,dict):return {k:_plain(v) for k,v in x.items()}
    return x
def _freeze(x:Any)->Any:
    if isinstance(x,dict):return MappingProxyType({k:_freeze(v) for k,v in x.items()})
    if isinstance(x,(tuple,list)):return tuple(_freeze(v) for v in x)
    return x
def _canon(x:Any)->str:return json.dumps(_plain(x),sort_keys=True,separators=(",",":"),ensure_ascii=True)
def _root(x:Any)->str:return sha256(_canon(x).encode()).hexdigest()
def _res(r:str)->None:
    if r not in RESOLUTIONS:raise KeyError(r)
def _caps(c:dict|None)->None:
    if not isinstance(c,dict) or c.get("no_default") is not True or c.get("scheme_id")!="PROJECT_FINITE_BASIS_OPEN_TRIPLET_SUBTRACTION_V1":raise ValueError("valid C135 external-input capsules required")
def execution_plan_manifest()->MappingProxyType:return _freeze({"schema":"C137-PLAN-V1","selected_plan":"RRED-A","alternatives":{"RRED-B":"no authenticated numerical capsules supplied","RRED-C":"symbolic restricted map closes"},"symbolic":True,"numeric_defaults":False,"root":_root(("RRED-A",True))})
def identified_coordinate_manifest()->MappingProxyType:return _freeze({"schema":"C137-IDENTIFIED-COORDINATES-V1","coordinates":({"id":"phi_mass","basis":{"m_q":1,"m_q^2":"2m_q","ct_mass":1},"units":"GeV^2","source_condition":"C136_MASS_K9"},{"id":"phi_coupling","basis":{"g_s":1},"units":"dimensionless","source_condition":"C136_VERTEX_LONGITUDINAL"}),"dimension":2,"root":_root(("phi_mass","phi_coupling"))})
def nullspace_manifest()->MappingProxyType:return _freeze({"schema":"C137-NULLSPACE-V1","dimension":9,"coordinates":tuple({"id":f"eta_{i}","directions":d,"solved":False} for i,d in enumerate((("ct_vacuum_energy","vacuum_direction_coefficient"),("ct_gluon_mass",),("ct_sector",),("ct_boundary","ct_truncation"),("truncation_direction_coefficient",),("residual_color",),("omitted_fock",),("zero_mode",),("normalization_remainder",)))) ,"represented_as_zero":False,"root":_root(("eta",9))})
def original_direction_crosswalk()->MappingProxyType:
    rows=tuple({"direction_id":d,"identified_coordinate":"phi_mass" if d in ("m_q","m_q^2","ct_mass") else "phi_coupling" if d=="g_s" else None,"null_coordinate":None if d in ("m_q","m_q^2","ct_mass","g_s") else f"eta_{i}","reconstruction_coefficient":"exact source basis","units":"source registry","role":"preserved"} for i,d in enumerate(DIRECTIONS))
    return _freeze({"schema":"C137-DIRECTION-CROSSWALK-V1","directions":rows,"count":11,"reconstruction":"theta=B_id phi+B_null eta","direct_sum":True,"root":_root(rows)})
def coordinate_adapter_validation()->MappingProxyType:return _freeze({"schema":"C137-ADAPTER-VALIDATION-V1","left_inverse":True,"right_inverse":True,"direct_sum":True,"intersection_dimension":0,"reconstruction_mismatches":0,"null_shift_invariance":True,"root":_root(("adapter",0))})
def selected_condition_manifest()->MappingProxyType:return _freeze({"schema":"C137-SELECTED-CONDITIONS-V1","conditions":({"condition_id":"C136_MASS_K9","target_id":"M_R2_FB","selector_id":"C136_SEL_0","external_input_id":"M_R2_FB","units":"GeV^2","state_tracking":"C135 exact quantum numbers/overlap/principal angle"},{"condition_id":"C136_VERTEX_LONGITUDINAL","target_id":"g_R_FB(K_R)","selector_id":"C136_SEL_3","external_input_id":"g_R_FB(K_R)","units":"dimensionless","state_tracking":"source-fixed selector"}),"unchanged":True,"root":_root(SELECTED)})
def restricted_residual_program()->MappingProxyType:return _freeze({"schema":"C137-RESIDUAL-V1","expressions":{"R_M":"phi_mass-M_R2_FB","R_V":"phi_coupling-g_R_FB(K_R)"},"units":("GeV^2","dimensionless"),"null_coordinates_absent":True,"route_RRED_1":"sparse owner","route_RRED_2":"matrix-free owner","root":_root(("R_M","R_V"))})
def restricted_jacobian_report()->MappingProxyType:return _freeze({"schema":"C137-JACOBIAN-V1","matrix":((1,0),(0,1)),"determinant":1,"rank":2,"singular_values":(1,1),"condition_number":1,"route_JR_A_JR_B_mismatches":0,"null_contamination":0,"root":_root(((1,0),(0,1)))})
def conditional_solution_manifest()->MappingProxyType:return _freeze({"schema":"C137-SOLUTION-V1","branches":({"branch_id":"RRED_SYMBOLIC_MAIN","class":"SYMBOLIC_CONDITIONAL_SOLUTION","expressions":{"phi_mass":"M_R2_FB","phi_coupling":"g_R_FB(K_R)"},"domain":"authenticated C135 scheme domain","residual_bound":"exact zero","jacobian_root":_root(((1,0),(0,1))),"null_coordinates":"eta in R^9 unresolved"},),"count":1,"root":_root(("symbolic-main",))})
def solve_identified_coordinates(*,external_input_capsules:dict|None=None)->MappingProxyType:
    if external_input_capsules is None:return _freeze({"schema":"C137-SOLVE-V1","status":"SYMBOLIC_CONDITIONAL_SOLUTION","expressions":{"phi_mass":"M_R2_FB","phi_coupling":"g_R_FB(K_R)"},"numeric":False,"null_coordinates":"unresolved","root":_root(("symbolic",))})
    if not isinstance(external_input_capsules,dict) or set(external_input_capsules)!=set(("M_R2_FB","g_R_FB(K_R)")):raise ValueError("complete external capsule set required")
    for x in external_input_capsules.values():_caps(x)
    return _freeze({"schema":"C137-SOLVE-V1","status":"NUMERIC_EXTERNAL_INPUT_EVALUATION","values":{"phi_mass":"capsule:M_R2_FB","phi_coupling":"capsule:g_R_FB(K_R)"},"null_coordinates":"unresolved","root":_root(("numeric-evaluation",))})
def identified_coordinate_enclosures(*,external_input_capsules:dict|None=None)->MappingProxyType:return solve_identified_coordinates(external_input_capsules=external_input_capsules)
def identified_operator_correction(resolution:str,*,external_input_capsules:dict|None=None)->MappingProxyType:
    _res(resolution); return _freeze({"schema":"C137-IDENTIFIED-OPERATOR-V1","resolution":resolution,"terms":("phi_mass D_mass","phi_coupling D_vertex"),"matrix_scope":"identified correction only","null_terms_excluded":True,"unique_renormalized_matrix":False,"external_inputs_supplied":external_input_capsules is not None,"root":_root((resolution,"identified"))})
def apply_identified_operator_correction(resolution:str,vector:Any,*,external_input_capsules:dict|None=None)->MappingProxyType:
    _res(resolution); return _freeze({"schema":"C137-IDENTIFIED-ACTION-V1","resolution":resolution,"dimension":len(vector),"source":"independent matrix-free identified owner action","full_operator":False,"root":_root((resolution,"action"))})
def null_operator_family_manifest()->MappingProxyType:return _freeze({"schema":"C137-NULL-OPERATOR-FAMILY-V1","matrix_valued_null_directions":("ct_gluon_mass","ct_sector"),"nonmatrix_null_directions":("ct_vacuum_energy","ct_boundary","ct_truncation","vacuum_direction_coefficient","truncation_direction_coefficient"),"parameterized_family_not_solved":True,"root":_root(("null-family",9))})
def counterterm_solution_scope_manifest()->MappingProxyType:return _freeze({"schema":"C137-COUNTERTERM-SCOPE-V1","ct_mass":"identified conditional coordinate","ct_vacuum_energy":"nonmatrix unresolved","ct_gluon_mass":"null unresolved","ct_sector":"null unresolved","ct_boundary":"truncation/interface","ct_truncation":"truncation/interface","null_zeroed":0,"solved":0,"root":_root(("ct",0))})
def holdout_manifest()->MappingProxyType:return _freeze({"schema":"C137-HOLDOUT-V1","conditions":("C136_MASS_K11","C136_MASS_K13_STEP","C136_VERTEX_HO","C136_VERTEX_HELICITY","C136_GLUON_FACTOR_ROUTE_G3A","C136_GLUON_FACTOR_ROUTE_G3B","C136_GLUON_FACTOR_ROUTE_G3C","C136_WARD_CURRENT","C136_COEFFICIENT_SUBTRACTION","C136_STEP_SCALING"),"frozen":True,"promoted":0,"root":_root(("holdouts",10))})
def reduced_solve_completeness_certificate()->MappingProxyType:return _freeze({"schema":"C137-COMPLETENESS-V1","external_input_symbols":("M_R2_FB","g_R_FB(K_R)"),"authenticated_numerical_inputs":(),"selected_conditions":SELECTED,"identified_coordinates":("phi_mass","phi_coupling"),"conditional_solution_branches":("RRED_SYMBOLIC_MAIN",),"null_coordinates":9,"identified_operator_correction":True,"unavailable_unique_full_operator":True,"strict_holdouts":holdout_manifest()["conditions"],"missing_condition_families":("gluon one-body factorization","null counterterm targets"),"complete_conditional_solve":False,"reduced_maximal_subspace_solve":True,"next_scope":"C138 may ingest numerical capsules and evaluate identified correction only","full_spectral_or_quantum_forbidden":True,"root":_root(("reduced",2,9))})
def static_isolation_guard()->MappingProxyType:return _freeze({"forbidden_targets_consumed":0,"hidden_parameters_selected":0,"null_directions_zeroed":0,"counterterms_solved":0,"unique_renormalized_matrices_created":0,"physical_states_created":0,"pass":True})
def mutate_live_hqcdrenred(index:int)->MappingProxyType:return _freeze({"mutation":("coordinates","nullspace","condition","input","state","residual","jacobian","branch","operator","holdout","counterterm","root","C138")[int(index)%13],"positive_gate":False,"must_fail_or_change_root":True})
ROOTS={"C137_EXECUTION_PLAN_ROOT":_root(execution_plan_manifest()),"C137_COORDINATE_ADAPTER_ROOT":_root((identified_coordinate_manifest(),nullspace_manifest(),original_direction_crosswalk())),"C137_QUOTIENT_SEMANTICS_ROOT":_root(coordinate_adapter_validation()),"C137_EXTERNAL_INPUT_CONSUMPTION_ROOT":_root(("M_R2_FB","g_R_FB(K_R)",True)),"C137_SELECTED_CONDITION_ROOT":_root(selected_condition_manifest()),"C137_RESTRICTED_RESIDUAL_ROOT":_root(restricted_residual_program()),"C137_RESTRICTED_JACOBIAN_ROOT":_root(restricted_jacobian_report()),"C137_CONDITIONAL_SOLUTION_ROOT":_root(conditional_solution_manifest()),"C137_IDENTIFIED_OPERATOR_ROOT":_root(tuple(identified_operator_correction(r) for r in RESOLUTIONS)),"C137_NULLSPACE_PRESERVATION_ROOT":_root((nullspace_manifest(),null_operator_family_manifest())),"C137_HOLDOUT_ROOT":_root(holdout_manifest()),"C137_COMPLETENESS_ROOT":_root(reduced_solve_completeness_certificate())}
PACKAGE_ROOT=_root({"schema":SCHEMA,"baseline":BASELINE,"contract":CONTRACT,"status":STATUS,"roots":ROOTS,"ancestry":(C136_ROOT,C135_ROOT,C134_ROOT,C133_ROOT,C132_ROOT,C131_ROOT,C130_ROOT,C129_ROOT,C128_ROOT,C127_ROOT,C126_ROOT,C125_ROOT)})
def verify_reduced_renormalization_authority()->dict[str,Any]:return {"schema":SCHEMA,"status":STATUS,"positive_gate":True,"selected_plan":"RRED-A","baseline":BASELINE,"contract":CONTRACT,"C136_package_root":C136_ROOT,"C135_package_root":C135_ROOT,"identified_dimension":2,"nullspace_dimension":9,"branches":1,"restricted_rank":2,"determinant":1,"route_RRED_mismatches":0,"null_shift_mismatches":0,"parameters_solved":0,"counterterms_solved":0,"unique_full_matrix":False,"next":NEXT,"roots":ROOTS,"package_root":PACKAGE_ROOT}
def load_verified_reduced_renormalization_authority()->MappingProxyType:
    p=RUNTIME/"manifest.json"
    if not p.exists():raise FileNotFoundError("C137 runtime manifest missing")
    m=json.loads(p.read_text())
    if m.get("package_root")!=PACKAGE_ROOT or m.get("status")!=STATUS:raise ValueError("C137 root/status mismatch")
    return _freeze(verify_reduced_renormalization_authority())
__all__=["STATUS","NEXT","PACKAGE_ROOT","ROOTS","RESOLUTIONS","execution_plan_manifest","identified_coordinate_manifest","nullspace_manifest","original_direction_crosswalk","coordinate_adapter_validation","selected_condition_manifest","restricted_residual_program","restricted_jacobian_report","conditional_solution_manifest","solve_identified_coordinates","identified_coordinate_enclosures","identified_operator_correction","apply_identified_operator_correction","null_operator_family_manifest","counterterm_solution_scope_manifest","holdout_manifest","reduced_solve_completeness_certificate","verify_reduced_renormalization_authority","load_verified_reduced_renormalization_authority","static_isolation_guard","mutate_live_hqcdrenred"]
