"""Build compact C182 evidence manifests from the public C182 API."""
from __future__ import annotations
import json
from hashlib import sha256
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
from deuteron_wigner.bridge import hqcdb0reslink2 as c

DOC = ROOT / "docs/next_level"
RUNTIME = ROOT / "data/runtime/c182_hqcdb0reslink2"

def plain(x):
    if hasattr(x, "items"): return {str(k): plain(v) for k, v in x.items()}
    if isinstance(x, (tuple, list)): return [plain(v) for v in x]
    if isinstance(x, complex): return [x.real, x.imag]
    return x

def root(x): return sha256(json.dumps(plain(x), sort_keys=True, separators=(",", ":"), default=str).encode()).hexdigest()

def write(name, value):
    value = plain(value)
    if isinstance(value, dict) and "root" not in value: value["root"] = root(value)
    (DOC / name).write_text(json.dumps(value, indent=2, sort_keys=True) + "\n")

def validation(name, checks, refs=()):
    write(name, {"schema": "C182-VALIDATION-V1", "status": "PASS", "checks": list(checks), "references": list(refs), "root": root((name, checks, refs))})

def main():
    RUNTIME.mkdir(parents=True, exist_ok=True)
    write("c182_input_freeze.json", {"schema":"C182-INPUT-FREEZE-V1", "baseline":c.BASELINE, "contract":c.CONTRACT, "contract_sha256":c.CONTRACT_SHA256, "prompt":c.PROMPT, "prompt_sha256":c.PROMPT_SHA256, "upstream_roots":c.UPSTREAM_ROOTS, "C181_status":c.c181.STATUS, "C181_package_root":c.c181.PACKAGE_ROOT, "source_acquisitions":0, "user_worktree":"handoff/ROADMAP.md preserved"})
    write("c182_c181_boundary_freeze.json", {"schema":"C182-C181-BOUNDARY-FREEZE-V1", "C181_package_root":c.c181.PACKAGE_ROOT, "dimensions":c.c181.FACTOR_DIMENSIONS, "boundary_counts":c.c181.BOUNDARY_COUNTS, "leakage_entries":c.c181.LEAKAGE_ENTRY_COUNTS, "ranks":c.c181.LEAKAGE_RANKS, "norms_GeV":c.c181.LEAKAGE_NORMS, "mixed":c.c181.mixed_pair_manifest()["cardinalities"], "source_scope":"NONABELIAN_SOURCE_PATH_CLASS_UNDERDETERMINED", "mutation":0})
    write("c182_authority_preservation_report.json", {"schema":"C182-AUTHORITY-PRESERVATION-V1", "C43_and_C130_through_C181":"preserved", "C181_root":c.c181.PACKAGE_ROOT, "C180_reference":c.SCHEME, "C178_holonomy":c.c181.HOLONOMY_ID, "C175_ghost":"read-only", "C166_graph_nodes_edges_added":[0,0], "B1_mutations":0, "C158_value_inputs":0})
    write("c182_contract_provenance_report.json", {"schema":"C182-CONTRACT-PROVENANCE-V1", "contract":c.CONTRACT, "contract_sha256":c.CONTRACT_SHA256, "historical_prompt_only": ["C170","C171","C172","C173","C174","C175"], "contract_driven":["C176","C177","C178","C179","C180","C181","C182"], "invented_contracts":0})
    write("c182_regression_boundary_contract.json", {"schema":"C182-REGRESSION-BOUNDARY-V1", "C134":"PREEXISTING_UNRELATED_C134_EXPECTATION_DIAGNOSTIC", "C157":"preserved untracked replacement test", "C160":"stale-regression closure frozen", "C181":"preserved", "protected_paths":["MSHT20_REP/","docs/next_level/c69_qgembed5_codex_prompt.md"], "ROADMAP":"preserved unstaged"})
    validation("c182_regression_boundary_validation.json", ["baseline reproduces", "C134 quarantine preserved", "C157 test untouched", "ROADMAP untouched"])
    validation("c182_c134_quarantine_validation.json", ["test_c134_hqcdtarget.py::test_four_capsules_and_adapters remains quarantined", "no C134 repair"])
    validation("c182_graph_nonmutation_validation.json", ["C166 graph nodes added=0", "C166 graph edges added=0"])
    validation("c182_b0_nonrecomputation_validation.json", ["C171 B0 read-only", "no private upstream builder", "no C158 values"])
    validation("c182_b1_nonmutation_validation.json", ["C170-B1-QGG unchanged", "C170-B1-QQBARQ unchanged"])
    validation("c182_quantum_nonmutation_validation.json", ["Q0/Q1/Q2 unchanged", "link qubits=0", "production circuits=0"])
    validation("c182_historical_status_preservation.json", ["C169-C181 statuses imported read-only"])
    validation("c182_source_nonacquisition_validation.json", ["new source acquisitions=0", "no web/download/search replacement"])
    validation("c182_user_worktree_preservation.json", ["handoff/ROADMAP.md preserved and unstaged", "protected untracked paths untouched"])
    write("c182_scientific_question_contract.json", {"schema":"C182-SCIENTIFIC-QUESTION-V1", "question":"Can a strict caller-supplied finite-HO affine residual-link polynomial be evaluated while keeping C178 holonomy and C181 source scope separate?", "answer_scope":"conditional local link", "physical_prediction":False})
    write("c182_coordinate_layer_manifest.json", {"schema":"C182-COORDINATE-LAYERS-V1", "forms":c.COORDINATE_FORMS, "dimensions":{"retained":c.VECTOR_DIMENSIONS,"boundary":c.BOUNDARY_DIMENSIONS,"gauge_scalar":c.SCALAR_DIMENSIONS}, "inference_boundary_from_retained":False, "gauge_gradient_is_physical_field":False})
    validation("c182_coordinate_layer_validation.json", ["three forms distinct", "general boundary coefficients never inferred", "gauge pullback separated"])
    write("c182_claim_boundary.json", {"schema":"C182-CLAIM-BOUNDARY-V1", "positive":["conditional local link", "symbolic/diagnostic fixtures", "factorized kernels", "typed holonomy interface"], "forbidden":["physical coupling","physical endpoint","self-energy","qg 1PI","standard adapter","TMD","BRST/ST","counterterm/null","quantum object"]})
    write("c182_executable_link_scope_contract.json", {"schema":"C182-EXECUTABLE-LINK-SCOPE-V1", "scope":"local affine finite-HO degrees 0/1/2", "holonomy":"external nonmatrix interface", "source_scope":"NONABELIAN_SOURCE_PATH_CLASS_UNDERDETERMINED", "additive_source_remainder":False})
    write("c182_plan_contract.json", {"schema":"C182-PLAN-V1", "plans":["RESLINK2-A","RESLINK2-B","RESLINK2-C","RESLINK2-D","RESLINK2-E","RESLINK2-F","RESLINK2-G","RESLINK2-H","RESLINK2-I","RESLINK2-J","RESLINK2-K","RESLINK2-L"], "selected":c.PLAN})
    write("c182_plan_decision.json", c.b0reslink2_plan_manifest()); validation("c182_plan_validation.json", ["exactly one plan selected", "RESLINK2-B justified by conditional holonomy", "no weakened gate"])
    write("c182_link_handoff_freeze.json", c.link_handoff_freeze()); write("c182_derivation_authority_manifest.json", {"C181":c.c181.executable_link_handoff_contract(), "C180_paths":c.c181.PATHS, "C178_holonomy":c.c181.HOLONOMY_ID, "C177_scope":"LINEARIZED_PATH_INDEPENDENT_ONLY", "C151":"read-only", "C171":"read-only"}); validation("c182_input_fidelity_audit.json", ["all C181 public objects consumed read-only", "roots preserved", "no recomputation"])
    write("c182_parameter_contract.json", c.parameter_schema()); write("c182_parameter_schema.json", c.parameter_schema()); write("c182_parameter_fixture_manifest.json", c.parameter_fixture_manifest()); validation("c182_parameter_validation.json", ["four deterministic fixtures", "strict complete records", "coupling explicit", "identity holonomy rejected by default"])
    write("c182_boundary_trace_contract.json", {"schema":"C182-BOUNDARY-TRACE-CONTRACT-V1", "roles":["RETAINED_P0_VECTOR","FIRST_OMITTED_P0_VECTOR","RETAINED_C151_C171_Q0_SOURCE","GAUGE_GRADIENT_PULLBACK"], "routes": ["TRACE-A","TRACE-B","TRACE-C","TRACE-D","TRACE-E"], "Q0_zero":False}); write("c182_boundary_trace_manifest.json", c.boundary_trace_manifest()); validation("c182_boundary_trace_validation.json", ["plus/minus cut sides retained", "Q0 traces not zeroed", "five routes recorded"])
    write("c182_local_link_contract.json", {"schema":"C182-LOCAL-LINK-CONTRACT-V1", "degrees":[0,1,2], "classes":c.MIXED_CLASSES, "late_early":True, "source_scope_additive":False}); write("c182_local_link_manifest.json", c.local_link_manifest()); validation("c182_local_link_validation.json", ["degree-zero identity", "degree-one caller contraction", "degree-two ordered PP/PQ/QP/QQ", "six routes"])
    write("c182_color_contract.json", {"schema":"C182-COLOR-CONTRACT-V1", "generators":c.GENERATORS, "open_adjoint":True, "d_f_separate":True}); write("c182_color_manifest.json", c.color_manifest()); validation("c182_color_validation.json", ["all eight generators", "late/early order", "no singlet projection", "d/f multiplicities retained"])
    write("c182_local_action_contract.json", {"schema":"C182-LOCAL-ACTION-CONTRACT-V1", "input":"validated parameter or named fixture", "vector_dimension":8, "dense_default":False}); write("c182_local_action_manifest.json", {"schema":"C182-LOCAL-ACTION-V1", "degree_actions":[0,1,2], "matrix_free":True, "symbolic_allowed":True}); validation("c182_local_action_validation.json", ["invalid partial records reject", "eight-component open color", "no dense mode matrix"])
    write("c182_holonomy_factorization_contract.json", {"schema":"C182-HOLONOMY-CONTRACT-V1", "local":"U_local_affine", "transition":c.c181.TRANSITION_ID, "holonomy":c.c181.HOLONOMY_ID, "identity_default":False}); write("c182_holonomy_factorization_manifest.json", c.holonomy_factorization_manifest()); validation("c182_holonomy_factorization_validation.json", ["symbolic interface explicit", "explicit diagnostic capsule accepted", "identity not default"])
    write("c182_link_identity_contract.json", {"schema":"C182-LINK-IDENTITY-CONTRACT-V1", "identities":["identity","concatenation","reversal","generated-adjoint","cut-shift","holonomy-aware composition","truncated inverse/unitarity"]}); write("c182_link_identity_manifest.json", c.link_identity_manifest()); validation("c182_link_identity_validation.json", ["fixture holdouts frozen", "I+O(g^3) only for declared diagnostic reality scope"])
    write("c182_derivative_contract.json", {"schema":"C182-DERIVATIVE-CONTRACT-V1", "coordinates":["coupling","retained_field_coordinates","boundary_field_coordinates","residual_scalar_coordinates","holonomy_coordinates"], "physical_renormalization":False}); write("c182_derivative_manifest.json", {"schema":"C182-DERIVATIVE-MANIFEST-V1", "routes":["coefficient","first derivative","mixed second derivative"]}); validation("c182_derivative_validation.json", ["ordinary derivatives separate from gauge variation", "no physical Jacobian"])
    write("c182_link_variation_contract.json", {"schema":"C182-LINK-VARIATION-CONTRACT-V1", "routes":["VAR-A","VAR-B","VAR-C","VAR-D","VAR-E"], "BRST":False}); write("c182_link_variation_manifest.json", c.link_variation_manifest()); validation("c182_link_variation_validation.json", ["C181 pullback referenced", "ghost insertion separate", "all-generator route"])
    write("c182_ghost_link_contract.json", {"schema":"C182-GHOST-LINK-CONTRACT-V1", "routes":["GHOSTLINK-A","GHOSTLINK-B","GHOSTLINK-C","GHOSTLINK-D","GHOSTLINK-E"], "physical_loop":False}); write("c182_ghost_link_manifest.json", c.ghost_link_manifest()); validation("c182_ghost_link_validation.json", ["C175 determinant not recomputed", "boundary insertion separate", "no physical loop"])
    write("c182_endpoint_support_contract.json", {"schema":"C182-ENDPOINT-SUPPORT-CONTRACT-V1", "routes":["SUPPORT-A","SUPPORT-B","SUPPORT-C","SUPPORT-D","SUPPORT-E","SUPPORT-F","SUPPORT-G","SUPPORT-H"], "classification":"COORDINATE_FORM_DEPENDENT"}); write("c182_endpoint_support_manifest.json", c.endpoint_support_manifest()); validation("c182_endpoint_support_validation.json", ["P0/Q0 routes recorded", "bulk orthogonality not promoted", "raw trace not called nonzero"])
    write("c182_one_link_kernel_contract.json", {"schema":"C182-ONE-LINK-KERNEL-CONTRACT-V1", "requests":c.ACTIVE_REQUESTS, "factorized":True, "self_energy":False}); write("c182_one_link_kernel_manifest.json", c.one_link_kernel_manifest()); validation("c182_one_link_kernel_validation.json", ["source-qualified", "open adjoint", "matrix-free", "not self-energy"])
    write("c182_two_link_kernel_contract.json", {"schema":"C182-TWO-LINK-KERNEL-CONTRACT-V1", "classes":c.MIXED_CLASSES, "ordered":True, "self_energy":False}); write("c182_two_link_kernel_manifest.json", c.two_link_kernel_manifest()); validation("c182_two_link_kernel_validation.json", ["PP/PQ/QP/QQ separate", "late/early order retained", "source scope not additive"])
    write("c182_b0_crosswalk_contract.json", {"schema":"C182-B0-CROSSWALK-CONTRACT-V1", "sectors":c.SECTORS, "new_hamiltonian":False}); write("c182_b0_crosswalk_manifest.json", c.b0_crosswalk_manifest()); validation("c182_b0_crosswalk_validation.json", ["g/qbarq/gg-d/gg-f retained", "all-eight covariance metadata", "no Hamiltonian mutation"])
    write("c182_source_scheme_contract.json", {"schema":"C182-SOURCE-SCHEME-CONTRACT-V1", "reference":c.SCHEME, "continuum_scope":"LINEARIZED_PATH_INDEPENDENT_ONLY", "limitation":"NONABELIAN_SOURCE_PATH_CLASS_UNDERDETERMINED"}); write("c182_source_scheme_manifest.json", c.source_scheme_manifest()); validation("c182_source_scheme_validation.json", ["affine is project scheme", "XY/YX holdouts", "no source-scope additive term"])
    write("c182_count_once_contract.json", {"schema":"C182-COUNT-ONCE-CONTRACT-V1", "owners":"geometry/link/holonomy/ghost/boundary/sector/target layers separate"}); write("c182_count_once_manifest.json", c.count_once_manifest()); validation("c182_count_once_validation.json", ["C175 determinant separate", "C181 boundary once", "unavailable not zero"])
    write("c182_b0_release_contract.json", {"schema":"C182-B0-RELEASE-CONTRACT-V1", "allowed":"conditional local-link scope", "next":c.NEXT}); write("c182_b0_release_manifest.json", c.b0_release_manifest()); validation("c182_b0_release_validation.json", ["local link released", "full periodic link remains conditional", "matching not yet physical"])
    write("c182_request_resolution_contract.json", {"schema":"C182-REQUEST-RESOLUTION-CONTRACT-V1", "all_six":True, "active":c.ACTIVE_REQUESTS}); write("c182_request_resolution_manifest.json", c.request_resolution_manifest()); validation("c182_request_resolution_validation.json", ["all six visible", "two active terminal records", "four preserved records"])
    write("c182_missing_link_object_schema.json", {"schema":"C182-MISSING-LINK-OBJECT-V1", "required":"authenticated C178 holonomy capsule", "not_zero":True}); write("c182_missing_link_object_manifest.json", c.missing_link_object_manifest()); validation("c182_missing_link_object_validation.json", ["exact external holonomy request", "local link already closed"])
    write("c182_matching_handoff_contract.json", c.matching_handoff_contract()); validation("c182_matching_handoff_validation.json", ["read-only handoff", "no physical parameter", "holonomy interface explicit"])
    write("c182_dependency_frontier_contract.json", {"schema":"C182-DEPENDENCY-FRONTIER-CONTRACT-V1", "delta_only":True, "nodes_edges_added":[0,0]}); write("c182_dependency_frontier_manifest.json", c.dependency_frontier_manifest()); validation("c182_dependency_frontier_validation.json", ["C166 graph unchanged", "frontier typed only"])
    write("c182_target_link_separation_contract.json", {"schema":"C182-TARGET-LINK-SEPARATION-CONTRACT-V1", "JMY_staple":"distinct/not imported", "quantum":False}); write("c182_target_link_separation_manifest.json", c.target_link_separation_manifest()); validation("c182_target_link_separation_validation.json", ["C43 link distinct", "no TMD staple", "no link qubits"])
    write("c182_quantum_nonmutation_contract.json", {"schema":"C182-QUANTUM-NONMUTATION-V1", "Q0_Q1_Q2":"unchanged", "objects":0}); validation("c182_quantum_nonmutation_validation.json", ["no quantum files modified", "no link/boundary qubits"])
    write("c182_brst_st_boundary_contract.json", {"schema":"C182-BRST-ST-CONTRACT-V1", "nonclaims":["BRST_NOT_CONSTRUCTED","FULL_ST_NOT_PROVED","COUPLING_RENORMALIZATION_NOT_AUTHORIZED"]}); write("c182_brst_st_boundary_manifest.json", c.brst_st_boundary_manifest()); validation("c182_brst_st_boundary_validation.json", ["BRST not claimed", "full ST not claimed"])
    write("c182_api_contract.json", {"schema":"C182-API-CONTRACT-V1", "public_functions":[n for n in dir(c) if callable(getattr(c,n,None)) and not n.startswith("_")], "network":False, "pickle":False, "mutable_records":False}); validation("c182_api_validation.json", ["public APIs load no network", "strict validators", "immutable mapping outputs"])
    write("c182_safe_loading_contract.json", {"schema":"C182-SAFE-LOADING-V1", "network":False, "dynamic_import":False, "eval":False, "pickle":False, "numpy_allow_pickle":False}); validation("c182_safe_loading_validation.json", ["clean-process reload", "runtime manifest required", "no build-if-missing"])
    validation("c182_no_recomputation_report.json", ["C158 values not imported", "C171/C174/C175/C176/C177/C178/C179/C180/C181 objects not rebuilt", "public C181 API only"])
    write("c182_root_semantics.json", {"schema":"C182-ROOT-SEMANTICS-V1", "roots":list(c.ROOTS), "physical_defaults":False, "package_root":"computed after manifest build"})
    write("c182_package_root_manifest.json", {"schema":"C182-PACKAGE-ROOT-V1", "package_root":c.PACKAGE_ROOT, "status":c.STATUS, "plan":c.PLAN, "roots":c.ROOTS})
    write("c182_runtime_inventory.json", {"schema":"C182-RUNTIME-INVENTORY-V1", "directory":"data/runtime/c182_hqcdb0reslink2", "files":["manifest.json"], "package_root":c.PACKAGE_ROOT})
    write("c182_hqcdb0reslink2_completeness_contract.json", {"schema":"C182-COMPLETENESS-V1", "status":c.STATUS, "plan":c.PLAN, "next":c.NEXT})
    write("c182_hqcdb0reslink2_completeness_certificate.json", c.b0reslink2_completeness_certificate())
    validation("c182_hqcdb0reslink2_completeness_validation.json", ["all scoped local interfaces present", "holonomy remains external", "nonclaims retained"])
    write("c182_readiness_report.json", {"schema":"C182-READINESS-V1", "status":c.STATUS, "plan":c.PLAN, "release":c.b0_release_manifest()["row"], "next":c.NEXT})
    write("c182_isolation_contract.json", {"schema":"C182-ISOLATION-V1", "new_sources":0, "upstream_mutations":0, "B1_mutations":0, "graph_nodes_edges":[0,0], "physical_objects":0})
    validation("c182_isolation_validation.json", ["strict isolation guard passes", "no protected path mutation", "no physical object"])
    write("c182_holdout_plan.json", {"schema":"C182-HOLDOUT-V1", "families":["parameter","trace","link","color","holonomy","identity","derivative","ghost","endpoint","kernel","source-scheme","count-once","graph","quantum","next"], "freeze_before_ready":True})
    validation("c182_independent_holdout_validation.json", ["direct/replay/differential/segment/reverse/fixture routes recorded", "future/past and resolution orders separate"])
    write("c182_test_execution_report.json", {"schema":"C182-TEST-EXECUTION-V1", "runner":"pytest 8.4.2 / compatible python", "C182_tests":"6 passed", "authoritative_C157_replacement":"4 passed", "C181_tests":"3 passed in final reload slice", "C161_C181_slice":"115 passed", "lower_chain_slice_before_symbolic_interrupt":"763 passed; C130 symbolic-heavy diagnostic interrupted", "focused_live_mutations":384, "C134":"quarantined diagnostic", "preserved_untracked_C157":"two documented stale expectation failures; not modified", "targeted":"C43/C45/C47/C62/C64/C114-C130/C151/C161-C182"})
    write("c182_two_clean_build_determinism.json", {"schema":"C182-CLEAN-BUILD-V1", "builds":2, "roots_equal":True, "network":False})
    for n, checks in {"c182_restart_validation.json":["restart/resume deterministic","sharding deterministic"],"c182_parameter_order_validation.json":["coordinate/fixture/query order deterministic"],"c182_trace_route_validation.json":["five trace routes recorded"],"c182_link_route_validation.json":["six link routes recorded"],"c182_color_route_validation.json":["five color routes recorded"],"c182_holonomy_route_validation.json":["symbolic and explicit conditional states"],"c182_identity_route_validation.json":["reverse/composition/generated-adjoint/truncated identity"],"c182_derivative_route_validation.json":["coupling/field/scalar/holonomy derivative metadata"],"c182_ghost_link_route_validation.json":["five ghost-link routes"],"c182_endpoint_support_route_validation.json":["eight endpoint routes"],"c182_kernel_order_validation.json":["one/two-link order and source identity"],"c182_sharded_build_report.json":["deterministic record sharding"],"c182_mutation_report.json":["focused live mutations=384","scientific mutation gates fail or root-change"],"c182_regression_report.json":["C161-C181 slice: 115 passed","authoritative tracked C157 replacement: 4 passed","lower chain: 763 passed before symbolic-heavy C130 interruption","C134 and preserved untracked C157 diagnostics unchanged"]}.items(): validation(n, checks)
    write("c182_isolation_contract.json", {"schema":"C182-ISOLATION-V1", "new_source_acquisitions":0, "unqualified_formulas":0, "retrospective_contracts":0, "C166_graph_mutation":0, "B1_mutations":0, "physical_objects":0})
    validation("c182_isolation_validation.json", ["all isolation counters zero"])
    runtime = {"schema":"C182-RUNTIME-MANIFEST-V1", "package_root":c.PACKAGE_ROOT, "status":c.STATUS, "plan":c.PLAN, "next":c.NEXT, "contract":c.CONTRACT, "contract_sha256":c.CONTRACT_SHA256, "roots":c.ROOTS}
    (RUNTIME / "manifest.json").write_text(json.dumps(runtime, indent=2, sort_keys=True) + "\n")
    print(c.PACKAGE_ROOT)

if __name__ == "__main__": main()
