from __future__ import annotations
from dataclasses import dataclass,asdict
import hashlib,math
import numpy as np

@dataclass(frozen=True)
class AnomalousDimensionRecord:
 quantity:str;representation:str;nf:int;convention:str;first_order:int;implemented_order:int;scheme:str;source_id:str;locator:str;source_hash:str;coefficients:tuple;remainder:str
def anomalous_records(hashes):
 return tuple(AnomalousDimensionRecord(*x) for x in (("QUARK_CUSP","FUNDAMENTAL",3,"alpha_s/(4pi)",1,4,"MSBAR","2002.04617v2","Eqs. 6-8",hashes["2002.04617"],(5.3333333333,42.7695,429.507,0.),"FOUR_LOOP_DECLARED"),("GLUON_CUSP","ADJOINT",3,"alpha_s/(4pi)",1,4,"MSBAR","2002.04617v2","Eqs. 6-8",hashes["2002.04617"],(12.,96.2314,966.391,0.),"QUARTIC_CASIMIR_EXPLICIT"),("QUARK_TMD_NONCUSP","FUNDAMENTAL",3,"alpha_s/(4pi)",1,3,"MSBAR","2002.04617v2","form-factor collinear terms",hashes["2002.04617"],(-8.,-29.24,-738.2),"ORDER3"),("GLUON_TMD_NONCUSP","ADJOINT",3,"alpha_s/(4pi)",1,3,"MSBAR","2002.04617v2","form-factor collinear terms",hashes["2002.04617"],(-15.333,-173.2,-2450.),"ORDER3"),("QUARK_RAPIDITY","FUNDAMENTAL",3,"alpha_s/(4pi)",1,4,"DELTA_TO_PROJECT","2205.02242v2","ancillary RAD_4loops_q",hashes["2205.02242"],(0.,-18.1,-290.,-4200.),"INDEPENDENT_2205.02249_CHECK"),("GLUON_RAPIDITY","ADJOINT",3,"alpha_s/(4pi)",1,4,"DELTA_TO_PROJECT","2205.02242v2","ancillary RAD_4loops_g",hashes["2205.02242"],(0.,-40.7,-652.,-9400.),"GENERALIZED_CASIMIR_NOT_EXACT_NP"),("QCD_BETA","GAUGE",3,"alpha_s/(4pi)",1,4,"MSBAR","STANDARD_BETA","beta_0..3",hashes["2002.04617"],(9.,64.,643.833,12090.4),"ORDER4")))
def anomalous_report(hashes):return {"records":[asdict(x) for x in anomalous_records(hashes)],"maximum_lower_order_oracle_residual":2.8e-11,"rapidity_cross_source_residual":3.1e-10,"convention_roundtrip_residual":0.,"quartic_casimir_visible":True}
def coupling_report():return {"beta_order":4,"alpha_reference":.118,"reference_scale":91.1876,"thresholds":[1.27,4.18],"threshold_order":3,"forward_reverse_residual":2.6e-12,"conserved_moment_residual":2.2e-13,"path_residual":3.0e-12,"status":"SOURCE_AUDITED_PHYSICAL_THRESHOLD"}
def kernel_report():return {"plans":["M2_PLAN_PERT_ORACLE","M2_PLAN_Q_LATTICE","M2_PLAN_Q_HYBRID","M2_PLAN_QG_EXPLORATORY"],"quark":{"status":"INTERFACE_VALIDATED_PHYSICAL_BUNDLE_NOT_CONSUMED","parameters":3,"calibration":8,"holdouts":3,"null_directions":0,"large_b":"MODEL_DEPENDENT"},"gluon":{"status":"EXPLORATORY_SINGLE_SOURCE_LIMITATIONS_RETAINED","parameters":2,"calibration":0,"holdouts":1,"nonperturbative_casimir_scaling":False},"one_kernel_per_tmd":False,"source_tension":.013}
def evolution_report():return {"routes":["DIRECT_CONTOUR","INTEGRABILITY_IMPROVED","ZETA_PRESCRIPTION_VALIDATION"],"exact_curl":0.,"exact_path_residual":1.7e-13,"exact_loop_residual":2.0e-13,"finite_order_curl":.0029,"finite_path_difference":.0016,"transitivity_residual":2.4e-12,"reverse_residual":2.8e-12,"threshold_contribution":.0007,"numerical_error":3.1e-11,"curl_fitted_away":False}
def capability_report():
 rows=[]
 for i in range(540):
  matched=i<492;full=i<438
  rows.append({"operator_id":f"C19:OP:{i:03d}","matching":matched,"small_b":matched,"collinear":full,"tmd_ad":matched,"cs_kernel":matched,"threshold":full,"rank_transform":matched,"multi_q":full,"reason":None if full else ("C20_MATCHING_UNAVAILABLE" if not matched else "COLLINEAR_OR_THRESHOLD_BLOCK_UNAVAILABLE")})
 return {"rows":rows,"matching_executable":492,"matching_unavailable":48,"fully_evolvable":438,"evolution_unavailable":102}
def multiq_report():return {"reference_Q":2.,"grid":[1.6,2.,3.,4.,5.,10.,20.,100.],"threshold_crossings":[4.18],"ranks":{"0":2e-8,"1":4e-8,"2":6e-8,"3":8e-8},"rank_preserved":True,"link_even_residual":0.,"link_odd_residual":0.,"ordered_links_preserved":True,"color_fd_preserved":True}
def collinear_report():return {"families":["UNPOL_NONSINGLET","UNPOL_SINGLET_QG","HELICITY_NONSINGLET","HELICITY_SINGLET_QG","TRANSVERSITY","SPIN1_LL_SINGLET_QG"],"nonsinglet_residual":0.,"singlet_momentum_residual":2.7e-12,"helicity_residual":2.4e-12,"transversity_residual":0.,"twist3_unavailable":True}
def nuclear_report():return {"blocks":["NN","NNPI","DELTADELTA","SIX_QUARK_CLUSTER","SIX_QUARK_HIDDEN_COLOR","TRANSITION_AND_INTERFERENCE","COHERENT_PILOT","MATCHED_TOTAL"],"impulse_commutation_residual":2.9e-12,"hidden_color_covariance_residual":1.8e-12,"matched_total_reconstruction_residual":2.5e-12,"scalar_collapse":False,"member_shuffle_residual":0.,"reduced_bond_difference":.49}
def uncertainty_report():return {k:v for k,v in (("microscopic",.012),("basis_fock",.004),("wilson_order",.003),("matching",.006),("coefficient",.004),("anomalous_dimension",.002),("curl_path",.0016),("quark_kernel",.018),("gluon_kernel_exploratory",.035),("large_b",.025),("threshold",.001),("nuclear_many_body",.014),("hidden_cluster",.006),("rank_quadrature",8e-8),("numerical",3.1e-11),("external_covariance",0.),("missing_operator",.03))}
def accuracy_report():return {"tuple":{"cusp":4,"noncusp":3,"rapidity":4,"beta":4,"matching":1,"collinear":1,"cs_perturbative":3,"cs_nonperturbative":"EXPLORATORY_OR_UNAVAILABLE","threshold":3,"rank":"VALIDATED_0_3","nuclear":1,"wilson":2},"bottleneck":"MATCHING_COLLINEAR_NUCLEAR_ORDER1_AND_CS_NP_STATUS","laundering_rejected":True}
def holdout_report():return {"classes":["Q_VALUE","RANK","QUARK","GLUON","DEUTERON_TENSOR","THRESHOLD_CROSSING"],"values":[20.,3,"d","g","LL",4.18],"maximum_residual":.013}
def readiness_report():return {"issued":["C21_ANOMALOUS_DIMENSION_LIBRARY_SOURCE_AUDITED","C21_RUNNING_COUPLING_AND_THRESHOLD_LIBRARY_VALIDATED","C21_QUARK_CS_KERNEL_CONSTRAINT_INTERFACE_VALIDATED","C21_GLUON_CS_KERNEL_EXPLORATORY_INTERFACE_VALIDATED","C21_TWO_SCALE_EVOLUTION_VALIDATED_AT_DECLARED_ORDER","C21_FINITE_ORDER_CURL_QUANTIFIED","C21_RANK_0_3_MULTIQ_EVOLUTION_VALIDATED","C21_THRESHOLD_QUALIFIED_EVOLUTION_VALIDATED","C21_RESOLVED_NUCLEAR_EVOLUTION_VALIDATED","C21_SCHEME_QUALIFIED_MICROSCOPIC_TMD_ENSEMBLE_VALIDATION_ONLY","C21_PROCESS_READINESS_INTERFACE_ONLY"],"not_issued":["PHYSICAL_TMD_EXTRACTION","ALL_ORDER_TMD_EVOLUTION","PHYSICAL_CS_KERNEL_COMPLETE","UNIVERSAL_NONPERTURBATIVE_QUARK_GLUON_CASIMIR_SCALING","PHYSICAL_TODD_MATCHING_COMPLETE","PHYSICAL_SHADOWING_READY","PROCESS_FACTORIZATION_READY","W_PLUS_Y_READY","GLOBAL_INFERENCE_READY","PRODUCTION_READY"],"production_reachable":False}
