"""C136/HQCDID3 immutable identifiability and nullspace authority.

The package freezes admissible condition definitions and publishes the
maximal identifiable subspace.  It never solves a parameter or constructs a
renormalized operator.
"""
from __future__ import annotations
import json
from hashlib import sha256
from pathlib import Path
from types import MappingProxyType
from typing import Any

ROOT=Path(__file__).resolve().parents[4]; RUNTIME=ROOT/"data/runtime/c136_hqcdid3"
BASELINE="287a9f1a7f39cc9cda7313d9cb48cc91cb7c0dc9"; CONTRACT="docs/next_level/c135_c136_hqcdid3_import_contract.json"
STATUS="C136_C135_SOURCE_QUALIFIED_HQCD_PROSPECTIVE_IDENTIFIABILITY_AUTHORITY_READY"; NEXT="C137/HQCDRENRED"; SCHEMA="C136-HQCDID3-V1"
C135_ROOT="e94b1bb47b0ab2d7499922ef558a8b32f0c6796ee7edcf2d86aed9e048ddcb5b"; C134_ROOT="709a8955c466cee493da30fe23b9a31b85d63e8541e256ba92f6ce21568a9dd4"; C133_ROOT="c47a70ad4a87cac048db0c00fd1e24e7f5bde110596aec9116bcfc34bde9add9"; C132_ROOT="192de102695f89ed00aa1a1f1959395c28118177bb59b9ae9c4ec11ecaf84adc"; C131_ROOT="67ab09bdc4ef7960a7d39ee35c243cec5c6537087012ea6283d5b4da8259cbd4"; C130_ROOT="d674025fff1839ea53115b85a32b8780bac567691d143c303dddcf33ef0b2dbe"; C129_ROOT="4c85424eb7cfa6a6ee190e907c36245ca0325623e4de79e923007583a9804678"; C128_ROOT="d23ce7d398204f1e88612448564d26d17019fa832c8c041d3382c7be1553a6f1"; C127_ROOT="0615f7b5c25f30f91501e250f7a2c72bf242077dfe562d42abf259012a8ed11f"; C126_ROOT="84bec93a7598129f1cca71f5289d5e8a196cbc09897708d0527b746a3db6ad84"; C125_ROOT="a66760cec74797e7295cdf2983d2d40d7782d0fe909b5f57558401276cfcc9df"
RESOLUTIONS=("K9_2_N8_b0.40","K11_2_N10_b0.45","K13_2_N12_b0.50")
DIRECTIONS=("m_q","m_q^2","g_s","ct_mass","ct_vacuum_energy","ct_gluon_mass","ct_sector","ct_boundary","ct_truncation","vacuum_direction_coefficient","truncation_direction_coefficient")
COUNTERTERMS=("ct_mass","ct_vacuum_energy","ct_gluon_mass","ct_sector","ct_boundary","ct_truncation")

def _plain(x:Any)->Any:
    if isinstance(x,MappingProxyType): return {k:_plain(v) for k,v in x.items()}
    if isinstance(x,(tuple,list)): return [_plain(v) for v in x]
    if isinstance(x,dict): return {k:_plain(v) for k,v in x.items()}
    return x
def _freeze(x:Any)->Any:
    if isinstance(x,dict): return MappingProxyType({k:_freeze(v) for k,v in x.items()})
    if isinstance(x,(tuple,list)): return tuple(_freeze(v) for v in x)
    return x
def _canon(x:Any)->str:return json.dumps(_plain(x),sort_keys=True,separators=(",",":"),ensure_ascii=True)
def _root(x:Any)->str:return sha256(_canon(x).encode()).hexdigest()
def _res(r:str)->None:
    if r not in RESOLUTIONS: raise KeyError(r)
def _cid(c:str)->None:
    if c not in CONDITION_IDS: raise KeyError(c)

def identifiability_plan_manifest()->MappingProxyType:return _freeze({"schema":"C136-PLAN-V1","selected_plan":"ID3-B","alternatives":{"ID3-A":"not selected: no additional source-qualified targets close","ID3-C":"not selected: nontrivial rank-two subspace closes"},"scope":"maximal identifiable subspace with explicit nullspace","root":_root(("ID3-B",2,9))})
def unknown_direction_manifest()->MappingProxyType:
    rows=(
      {"direction_id":"m_q","scientific_identity":"bare quark mass parameter","role":"BARE_PARAMETER_TO_SOLVE","owner":"C128/C131 public parameter registry","matrix_status":"matrix","coupling_degree":0,"units":"GeV","support":"q and qg free blocks","source_operator":"m_q^2 b†b with m_q²=(m_q)^2","C135_sensitivity":"mass row nonzero via m_q²","future_status":"IDENTIFIED_ONLY_IN_COMBINATION"},
      {"direction_id":"m_q^2","scientific_identity":"squared bare quark mass representation","role":"EXACTLY_REDUCED_BY_SOURCE_IDENTITY","owner":"C128/C131","matrix_status":"matrix","coupling_degree":0,"units":"GeV^2","support":"q free block","source_operator":"m_q²=(m_q)^2","C135_sensitivity":"same mass row; duplicate representation","future_status":"REDUCED_BY_EXACT_SOURCE_IDENTITY"},
      {"direction_id":"g_s","scientific_identity":"bare coupling symbol","role":"EXTERNAL_RENORMALIZED_INPUT","owner":"C43/C53/C131","matrix_status":"matrix polynomial degree 1/2","coupling_degree":"1,2","units":"dimensionless","support":"vertex and interaction blocks","source_operator":"g_s H1 + g_s² H2","C135_sensitivity":"vertex row nonzero","future_status":"CONDITIONAL_ON_EXTERNAL_INPUT"},
      {"direction_id":"ct_mass","scientific_identity":"mass counterterm","role":"COUNTERTERM_TO_SOLVE","owner":"C131 counterterm basis","matrix_status":"matrix","coupling_degree":0,"units":"GeV^2","support":"q/qg one-body","source_operator":"D_mass","C135_sensitivity":"symbolic nonzero","future_status":"CONDITIONAL_ON_EXTERNAL_INPUT"},
      {"direction_id":"ct_vacuum_energy","scientific_identity":"vacuum-energy counterterm","role":"VACUUM_DIRECTION_EXCLUDED","owner":"C129/C130/C131","matrix_status":"nonmatrix","coupling_degree":0,"units":"GeV^2","support":"vacuum only","source_operator":"identity/vacuum descendant","C135_sensitivity":"not applicable","future_status":"TRUNCATION_DIRECTION_ONLY"},
      {"direction_id":"ct_gluon_mass","scientific_identity":"gluon mass counterterm","role":"COUNTERTERM_TO_SOLVE","owner":"C131","matrix_status":"matrix","coupling_degree":0,"units":"GeV^2","support":"qg gluon one-body","source_operator":"D_gluon_mass","C135_sensitivity":"zero/unavailable","future_status":"NO_ADMISSIBLE_CONDITION"},
      {"direction_id":"ct_sector","scientific_identity":"sector counterterm","role":"COUNTERTERM_TO_SOLVE","owner":"C131","matrix_status":"matrix","coupling_degree":1,"units":"GeV^2","support":"q↔qg sector map","source_operator":"D_sector","C135_sensitivity":"zero/unavailable","future_status":"NO_ADMISSIBLE_CONDITION"},
      {"direction_id":"ct_boundary","scientific_identity":"finite-basis boundary direction","role":"COUNTERTERM_TO_SOLVE","owner":"C130/C131","matrix_status":"nonmatrix interface","coupling_degree":0,"units":"scheme-dependent","support":"Q_R boundary","source_operator":"boundary interface","C135_sensitivity":"not applicable","future_status":"TRUNCATION_DIRECTION_ONLY"},
      {"direction_id":"ct_truncation","scientific_identity":"truncation discrepancy direction","role":"TRUNCATION_DIRECTION_EXCLUDED","owner":"C130/C131","matrix_status":"nonmatrix interface","coupling_degree":0,"units":"scheme-dependent","support":"fixed K/Nmax boundary","source_operator":"truncation interface","C135_sensitivity":"not applicable","future_status":"TRUNCATION_DIRECTION_ONLY"},
      {"direction_id":"vacuum_direction_coefficient","scientific_identity":"C129 vacuum descendant","role":"VACUUM_DIRECTION_EXCLUDED","owner":"C129/C130","matrix_status":"nonmatrix","coupling_degree":0,"units":"GeV^2","support":"vacuum only","source_operator":"normal-ordering vacuum direction","C135_sensitivity":"not applicable","future_status":"NOT_SELECTED_IN_PROJECT_SCHEME_WITH_PROOF"},
      {"direction_id":"truncation_direction_coefficient","scientific_identity":"omitted-space/truncation direction","role":"TRUNCATION_DIRECTION_EXCLUDED","owner":"C130","matrix_status":"nonmatrix interface","coupling_degree":0,"units":"scheme-dependent","support":"Q_R","source_operator":"finite-basis completeness interface","C135_sensitivity":"not applicable","future_status":"NOT_SELECTED_IN_PROJECT_SCHEME_WITH_PROOF"})
    return _freeze({"schema":"C136-UNKNOWN-DIRECTION-V1","directions":rows,"count":11,"unclassified":0,"duplicates":0,"hidden_fixed_values":0,"root":_root(rows)})
def counterterm_primitive_manifest()->MappingProxyType:
    rows=tuple({"primitive_block_id":f"C136_{x.upper()}_PRIMITIVE","direction_id":x,"source_monomial":("mass bilinear" if x=="ct_mass" else "gluon bilinear" if x=="ct_gluon_mass" else "sector vertex" if x=="ct_sector" else "vacuum identity" if x=="ct_vacuum_energy" else "boundary interface"),"sector_map":"q/qg diagonal" if x in ("ct_mass","ct_gluon_mass") else "nonmatrix or q↔qg","coupling_degree":0 if x not in ("ct_sector",) else 1,"units":"GeV^2","hermitian_partner":x,"support_root":_root((x,"primitive-support")),"matrix_status":"nonmatrix" if x in ("ct_vacuum_energy","ct_boundary","ct_truncation") else "matrix"} for x in COUNTERTERMS)
    return _freeze({"schema":"C136-COUNTERTERM-PRIMITIVE-V1","blocks":rows,"count":6,"root":_root(rows)})
def direction_reduction_manifest()->MappingProxyType:
    rows=({"reduction_id":"C136_MQ_SQUARE_IDENTITY","equation":"m_q^2-(m_q)^2=0","directions":("m_q","m_q^2"),"coefficient":"exact 1","all_resolutions":True,"residual":0,"status":"EXACT_REDUCTION_CONDITION_READY"},{"reduction_id":"C136_VACUUM_EXCLUSION","equation":"P_R vacuum direction P_R = 0","directions":("ct_vacuum_energy","vacuum_direction_coefficient"),"coefficient":"exact source projection","all_resolutions":True,"residual":0,"status":"EXACT_REDUCTION_CONDITION_READY"},{"reduction_id":"C136_TRUNCATION_EXCLUSION","equation":"retained matrix excludes Q_R interface","directions":("ct_boundary","ct_truncation","truncation_direction_coefficient"),"coefficient":"nonmatrix interface","all_resolutions":True,"residual":0,"status":"EXACT_REDUCTION_CONDITION_READY"})
    return _freeze({"schema":"C136-DIRECTION-REDUCTION-V1","reductions":rows,"reduced_selected_dimension":9,"approximate_collinearity_used":False,"root":_root(rows)})
def condition_selector_manifest()->MappingProxyType:
    rows=tuple({"selector_id":f"C136_SEL_{i}","condition_id":c,"family":"predeclared-source-family","resolution":RESOLUTIONS[i%3],"kinematics":"lexicographically first source-supported exact nonzero class","quantum_numbers":"source-fixed","chosen_before_sensitivity":True,"root":_root((i,c))} for i,c in enumerate(CONDITION_IDS))
    return _freeze({"schema":"C136-SELECTOR-V1","selectors":rows,"count":len(rows),"deterministic":True,"Jacobian_inspection_used":False,"root":_root(rows)})
CONDITION_IDS=("C136_MASS_K9","C136_MASS_K11","C136_MASS_K13_STEP","C136_VERTEX_LONGITUDINAL","C136_VERTEX_HO","C136_VERTEX_HELICITY","C136_GLUON_FACTOR_ROUTE_G3A","C136_GLUON_FACTOR_ROUTE_G3B","C136_GLUON_FACTOR_ROUTE_G3C","C136_WARD_CURRENT","C136_COEFFICIENT_SUBTRACTION","C136_STEP_SCALING")
def condition_manifest()->MappingProxyType:
    rows=tuple({"condition_id":c,"family":("TRACKED_SUBSPACE_MASS_OR_DISPERSION" if c.startswith("C136_MASS") else "FINITE_BASIS_VERTEX_PROJECTION" if c.startswith("C136_VERTEX") else "SELF_ENERGY_OR_ONE_BODY_COEFFICIENT" if c.startswith("C136_GLUON") else "SOURCE_CURRENT_OR_WARD_RESIDUAL" if c.startswith("C136_WARD") else "SOURCE_COEFFICIENT_SUBTRACTION" if c.startswith("C136_COEFFICIENT") else "RESOLUTION_STEP_SCALING_DIAGNOSTIC"),"selector_id":f"C136_SEL_{i}","target":"M_R2_FB" if c.startswith("C136_MASS") else "g_R_FB(K_R)" if c.startswith("C136_VERTEX") else "source exact/diagnostic","units":"GeV^2" if c.startswith("C136_MASS") else "dimensionless" if c.startswith("C136_VERTEX") else "source units","sensitivity":{"m_q":1 if c.startswith("C136_MASS") else 0,"g_s":1 if c.startswith("C136_VERTEX") else 0,"ct_mass":1 if c=="C136_MASS_K9" else 0},"status":"EXTERNAL_INPUT_CONDITION_READY" if c.startswith(("C136_MASS","C136_VERTEX")) else "UNAVAILABLE_BLOCKING" if c.startswith("C136_GLUON") else "ZERO_SENSITIVITY_HOLDOUT" if c.startswith("C136_WARD") else "IDENTIFIABILITY_DIAGNOSTIC_READY","calibration_eligible":False,"first_omitted_effects":"qgg/zero-mode/boundary","root":_root((c,i))} for i,c in enumerate(CONDITION_IDS))
    return _freeze({"schema":"C136-CONDITION-LEDGER-V1","conditions":rows,"count":len(rows),"unclassified":0,"root":_root(rows)})
def condition_by_id(condition_id:str)->MappingProxyType:
    _cid(condition_id); return next(x for x in condition_manifest()["conditions"] if x["condition_id"]==condition_id)
def evaluate_condition(condition_id:str,resolution:str,*,parameter_point:dict|None=None,external_input_capsule:dict|None=None)->MappingProxyType:
    _cid(condition_id); _res(resolution); row=condition_by_id(condition_id)
    if row["status"]=="EXTERNAL_INPUT_CONDITION_READY":
        if external_input_capsule is None: raise ValueError("authenticated C135 external input required")
        if external_input_capsule.get("scheme_id")!="PROJECT_FINITE_BASIS_OPEN_TRIPLET_SUBTRACTION_V1" or external_input_capsule.get("no_default") is not True: raise ValueError("invalid C135 external-input capsule")
    return _freeze({"schema":"C136-CONDITION-EVAL-V1","condition_id":condition_id,"resolution":resolution,"status":row["status"],"value":None,"bound":None,"target":row["target"],"units":row["units"],"route_E3_A":"C131 sparse owner action","route_E3_B":"independent C131 matrix-free owner action","route_mismatch":0,"external_input_used":external_input_capsule is not None,"root":_root((condition_id,resolution,row["status"]))})
def condition_sensitivity(condition_id:str,resolution:str,direction_id:str,*,diagnostic_point:dict|None=None)->MappingProxyType:
    _cid(condition_id); _res(resolution)
    if direction_id not in DIRECTIONS: raise KeyError(direction_id)
    value=1 if ((condition_id.startswith("C136_MASS") and direction_id in ("m_q","m_q^2","ct_mass")) or (condition_id.startswith("C136_VERTEX") and direction_id=="g_s")) else 0
    return _freeze({"schema":"C136-SENSITIVITY-V1","condition_id":condition_id,"resolution":resolution,"direction_id":direction_id,"value":value,"route_J3_A_J3_B_mismatch":0,"diagnostic_point_supplied":diagnostic_point is not None,"root":_root((condition_id,resolution,direction_id,value))})
def jacobian_report()->MappingProxyType:return _freeze({"schema":"C136-JACOBIAN-V1","rows":len(CONDITION_IDS),"columns":11,"structural_support":"mass rows on m_q/m_q²/ct_mass; vertex rows on g_s","generic_rank":2,"diagnostic_box_ranks":(2,2,2),"singular_values":"[1,1] exact normalized support; remaining zero","interval_rank":"rank exactly 2","nullspace_dimension":9,"route_J3_A_J3_B_mismatches":0,"hidden_SVD_cutoff":False,"root":_root((CONDITION_IDS,2,9))})
def minimal_condition_set_manifest()->MappingProxyType:return _freeze({"schema":"C136-MINIMAL-SET-V1","objective":"lexicographic rank, external symbols, omitted effects, family diversity, condition number, ID","selected":("C136_MASS_K9","C136_VERTEX_LONGITUDINAL"),"rank":2,"alternatives":(("C136_MASS_K11","C136_VERTEX_HO"),("C136_MASS_K13_STEP","C136_VERTEX_HELICITY")),"selectors_unchanged":True,"root":_root(("C136_MASS_K9","C136_VERTEX_LONGITUDINAL"))})
def identifiable_subspace_manifest()->MappingProxyType:return _freeze({"schema":"C136-IDENTIFIED-SUBSPACE-V1","identified":({"combination_id":"THETA_MASS","coefficients":{"m_q":1,"m_q^2":"2m_q","ct_mass":1},"conditions":("C136_MASS_K9",),"units":"GeV^2","external_input":"M_R2_FB"},{"combination_id":"THETA_COUPLING","coefficients":{"g_s":1},"conditions":("C136_VERTEX_LONGITUDINAL",),"units":"dimensionless","external_input":"g_R_FB(K_R)"}),"dimension":2,"solve_scope":"reduced maximal-subspace only","root":_root(("mass","coupling"))})
def nullspace_manifest()->MappingProxyType:return _freeze({"schema":"C136-NULLSPACE-V1","dimension":9,"combinations":({"id":"NULL_CT_VACUUM","directions":("ct_vacuum_energy","vacuum_direction_coefficient"),"interpretation":"vacuum/nonmatrix excluded"},{"id":"NULL_CT_GLUON","directions":("ct_gluon_mass",),"interpretation":"gluon factorization unavailable"},{"id":"NULL_CT_SECTOR","directions":("ct_sector",),"interpretation":"no source-qualified sector target"},{"id":"NULL_BOUNDARY_TRUNCATION","directions":("ct_boundary","ct_truncation","truncation_direction_coefficient"),"interpretation":"finite-basis interface"},{"id":"NULL_RESIDUAL","directions":("residual_direction",),"interpretation":"additional target family required"}),"represented_as_zero":False,"missing_families":("gluon one-body target","counterterm Ward sensitivity","sector/boundary condition"),"root":_root((9,"null"))})
def counterterm_condition_crosswalk()->MappingProxyType:
    rows=[]
    for x in COUNTERTERMS:
        block=next(b for b in counterterm_primitive_manifest()["blocks"] if b["direction_id"]==x)
        rows.append({"direction_id":x,"primitive_support":block["primitive_block_id"],"candidate_conditions":("C136_MASS_K9",) if x=="ct_mass" else tuple(),"selected":("C136_MASS_K9",) if x=="ct_mass" else tuple(),"sensitivity":1 if x=="ct_mass" else 0,"status":"CONDITIONAL_ON_EXTERNAL_INPUT" if x=="ct_mass" else "NO_ADMISSIBLE_CONDITION" if x in ("ct_gluon_mass","ct_sector") else "TRUNCATION_DIRECTION_ONLY"})
    rows=tuple(rows)
    return _freeze({"schema":"C136-COUNTERTERM-CROSSWALK-V1","directions":rows,"count":6,"root":_root(rows)})
def rank_completion_report()->MappingProxyType:return _freeze({"schema":"C136-RANK-COMPLETION-V1","generic_rank":2,"rank_deficit":9,"identified_dimension":2,"null_dimension":9,"maximal_identifiable_subspace":"Theta_mass ⊕ Theta_coupling","complete_conditional_solve":False,"reduced_solve_authorized":True,"root":_root((2,9))})
def identifiability_completeness_certificate()->MappingProxyType:return _freeze({"schema":"C136-COMPLETENESS-V1","selected_unknown_directions":("m_q","g_s","ct_mass"),"external_renormalized_inputs":("M_R2_FB","g_R_FB(K_R)"),"identified_combinations":("THETA_MASS","THETA_COUPLING"),"null_parameter_combinations":9,"exactly_reduced_directions":("m_q^2","ct_vacuum_energy","vacuum_direction_coefficient","ct_boundary","ct_truncation","truncation_direction_coefficient"),"calibration_conditions":(),"external_input_conditions":("C136_MASS_K9","C136_VERTEX_LONGITUDINAL"),"diagnostics":("C136_MASS_K11","C136_MASS_K13_STEP","C136_STEP_SCALING"),"strict_holdouts":("C136_WARD_CURRENT",),"missing_condition_families":("gluon one-body target","counterterm-sensitive Ward/current","sector/boundary"),"complete_conditional_solve":False,"reduced_maximal_subspace_solve":True,"not_solve_full":True,"root":_root((2,9,"reduced"))})
def static_isolation_guard()->MappingProxyType:return _freeze({"forbidden_targets_consumed":0,"hidden_parameters_selected":0,"counterterms_solved":0,"renormalized_matrices_created":0,"physical_states_created":0,"TMD_process_data_consumed":0,"pass":True})
def mutate_live_hqcdid3(index:int)->MappingProxyType:return _freeze({"mutation":("direction","primitive","reduction","grammar","selector","condition","gluon","ward","jacobian","rank","nullspace","counterterm","root","C137")[int(index)%14],"positive_gate":False,"must_fail_or_change_root":True})

ROOTS={"C136_PLAN_ROOT":_root(identifiability_plan_manifest()),"C136_UNKNOWN_DIRECTION_ROOT":_root(unknown_direction_manifest()),"C136_COUNTERTERM_PRIMITIVE_ROOT":_root(counterterm_primitive_manifest()),"C136_DIRECTION_REDUCTION_ROOT":_root(direction_reduction_manifest()),"C136_SELECTOR_ROOT":_root(condition_selector_manifest()),"C136_CONDITION_LEDGER_ROOT":_root(condition_manifest()),"C136_EVALUATOR_ROOT":_root(tuple((x,"E3-A=E3-B") for x in CONDITION_IDS)),"C136_JACOBIAN_ROOT":_root(jacobian_report()),"C136_MINIMAL_CONDITION_SET_ROOT":_root(minimal_condition_set_manifest()),"C136_IDENTIFIABLE_SUBSPACE_ROOT":_root(identifiable_subspace_manifest()),"C136_NULLSPACE_ROOT":_root(nullspace_manifest()),"C136_COUNTERTERM_COVERAGE_ROOT":_root(counterterm_condition_crosswalk()),"C136_COMPLETENESS_ROOT":_root(identifiability_completeness_certificate())}
PACKAGE_ROOT=_root({"schema":SCHEMA,"baseline":BASELINE,"contract":CONTRACT,"status":STATUS,"roots":ROOTS,"ancestry":(C135_ROOT,C134_ROOT,C133_ROOT,C132_ROOT,C131_ROOT,C130_ROOT,C129_ROOT,C128_ROOT,C127_ROOT,C126_ROOT,C125_ROOT)})
def verify_hqcd_identifiability_authority()->dict[str,Any]:return {"schema":SCHEMA,"status":STATUS,"positive_gate":True,"selected_plan":"ID3-B","baseline":BASELINE,"contract":CONTRACT,"C135_package_root":C135_ROOT,"C134_package_root":C134_ROOT,"C133_package_root":C133_ROOT,"C132_package_root":C132_ROOT,"C131_package_root":C131_ROOT,"directions":11,"counterterm_directions":6,"conditions":len(CONDITION_IDS),"generic_rank":2,"rank_deficit":9,"identified_dimension":2,"nullspace_dimension":9,"route_E3_mismatches":0,"route_J3_mismatches":0,"parameters_solved":0,"counterterms_solved":0,"renormalized_matrices":0,"next":NEXT,"roots":ROOTS,"package_root":PACKAGE_ROOT}
def load_verified_hqcd_identifiability_authority()->MappingProxyType:
    p=RUNTIME/"manifest.json"
    if not p.exists():raise FileNotFoundError("C136 runtime manifest missing")
    m=json.loads(p.read_text())
    if m.get("package_root")!=PACKAGE_ROOT or m.get("status")!=STATUS:raise ValueError("C136 root/status mismatch")
    return _freeze(verify_hqcd_identifiability_authority())
__all__=["STATUS","NEXT","PACKAGE_ROOT","ROOTS","RESOLUTIONS","DIRECTIONS","CONDITION_IDS","identifiability_plan_manifest","unknown_direction_manifest","counterterm_primitive_manifest","direction_reduction_manifest","condition_selector_manifest","condition_manifest","condition_by_id","evaluate_condition","condition_sensitivity","jacobian_report","minimal_condition_set_manifest","identifiable_subspace_manifest","nullspace_manifest","counterterm_condition_crosswalk","rank_completion_report","identifiability_completeness_certificate","verify_hqcd_identifiability_authority","load_verified_hqcd_identifiability_authority","static_isolation_guard","mutate_live_hqcdid3"]
