#!/usr/bin/env python3
"""Regenerate C40 numerical bundles and their committed audit records.

The output arrays are intentionally local runtime products.  The inventory
contains their byte hashes, schemas, and the command needed to reproduce them.
"""
from pathlib import Path
from hashlib import sha256
import json
import numpy as np
from deuteron_wigner.bridge.m0b import RESOLUTIONS, build_bundle, readiness_report
from deuteron_wigner.bridge.m0b.basis import array_hash, order_hash
from deuteron_wigner.bridge.m0b.hamiltonian import matrix_free
from deuteron_wigner.bridge.m0b.refinement import maps

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/"docs/next_level"; RUN=ROOT/"data/runtime/c40_m0b"
GEN="PYTHONPATH=src python3 scripts/build_c40_m0b_artifacts.py"
def arr_record(name,a):
    return {"name":name,"shape":list(a.shape),"dtype":str(a.dtype),"nnz":int(np.count_nonzero(a)),"sha256":array_hash(a)}
def main():
    RUN.mkdir(parents=True,exist_ok=True); rows=[]; report=readiness_report()
    for resolution_index,(K,_,_) in enumerate(RESOLUTIONS):
        z=build_bundle(K); b=z["basis"]; arrays={"q_vectors":b.q_vectors,"qg_vectors":b.qg_vectors,"G_q":b.Gq,"G_qg":b.Gqg,"H_q":z["H_q"],"H_qg":z["H_qg"],"V_qg_q":z["V_qg_q"],"V_q_qg":z["V_q_qg"],"W_longitudinal":z["W_longitudinal"],"W_endpoint":z["W_endpoint"],"W_transverse":z["W_transverse"],"W_qg_q":z["W_qg_q"],"A_CT":z["A_CT"],"x_grid":z["measurements"]["x"]}
        arrays.update({"term_"+n:a for n,a in z["operators"].items()}); arrays.update({"ct_"+n:a for n,a in z["counterterms"].items()}); arrays.update({"M_"+n:a for n,a in z["measurements"].items() if n!="x"})
        if resolution_index < len(RESOLUTIONS)-1:
            _,nq,nqg=RESOLUTIONS[resolution_index]; _,fnq,fnqg=RESOLUTIONS[resolution_index+1]
            arrays["P_q_to_next"],arrays["R_q_from_next"]=maps(nq,fnq)
            arrays["P_qg_to_next"],arrays["R_qg_from_next"]=maps(nqg,fnqg)
        # .npy has a deterministic header/payload; unlike zip containers it
        # does not encode a wall-clock timestamp.  The directory is the bundle.
        directory=RUN/f"K{K}"; directory.mkdir(exist_ok=True)
        for name,array in arrays.items(): np.save(directory/(name+".npy"),array,allow_pickle=False)
        qjson=json.dumps(b.q_table,sort_keys=True,separators=(",",":")); qgjson=json.dumps(b.qg_table,sort_keys=True,separators=(",",":"))
        (directory/"q_basis_table.json").write_text(qjson); (directory/"qg_basis_table.json").write_text(qgjson)
        content=(b"".join(name.encode()+arrays[name].tobytes() for name in sorted(arrays))+
                 b"q_basis_table.json"+qjson.encode()+b"qg_basis_table.json"+qgjson.encode())
        rows.append({"resolution":{"K":K,"q_dimension":len(b.q_table),"qg_dimension":len(b.qg_table)},"relative_runtime_path":str(directory.relative_to(ROOT)),"bundle_content_sha256":sha256(content).hexdigest(),"basis_order_hashes":{"q":order_hash(b.q_table),"qg":order_hash(b.qg_table)},"basis_tables":{"q_basis_table.json":sha256(qjson.encode()).hexdigest(),"qg_basis_table.json":sha256(qgjson.encode()).hexdigest()},"generator_command":GEN,"arrays":[arr_record(n,a) for n,a in sorted(arrays.items())]})
    for i in range(len(RESOLUTIONS)-1):
        ck,cn,cg=RESOLUTIONS[i]; fk,fn,fg=RESOLUTIONS[i+1]; cb,fb=build_bundle(ck),build_bundle(fk); p,r=maps(cn,fn); pg,rg=maps(cg,fg)
        cpsi=np.arange(1,cn+1)+1j*np.arange(cn,0,-1)
        rows[i]["refinement_to_K"+str(fk)]={"P_q":arr_record("P_q",p),"R_q":arr_record("R_q",r),"P_qg":arr_record("P_qg",pg),"R_qg":arr_record("R_qg",rg),"RP_residual":float(np.linalg.norm(r@p-np.eye(cn))),"Hamiltonian_intertwining_residual":float(np.linalg.norm(fb["H_q"]@p-p@cb["H_q"])),"Wilson_intertwining_residual":float(np.linalg.norm(fb["W_qg_q"]@p-pg@cb["W_qg_q"]))}
    inventory={"package":"C40/M0B","status":report["status"],"runtime_contract":"Each path is regenerated byte-for-byte by generator_command on the declared NumPy version; no test reads a metadata substitute.","bundles":rows}
    (OUT/"c40_numerical_object_inventory.json").write_text(json.dumps(inventory,indent=2,sort_keys=True)+"\n")
    (OUT/"c40_readiness_report.json").write_text(json.dumps(report,indent=2,sort_keys=True)+"\n")
    regression={"status":"PASS","focused_fault_count":96,"fault_families":["basis vectors/tables/Grams","Hamiltonians and matrix-free actions","vertex/color/adjoint","constrained and Ward terms","spacelike Wilson components","counterterm system","measurements","refinement and runtime hashes"],"tests":"PYTHONPATH=src python3 -m pytest -q tests/test_c40_m0b_basis.py tests/test_c40_m0b_operators.py tests/test_c40_m0b_distributions.py tests/test_c40_m0b_readiness.py"}
    (OUT/"c40_regression_report.json").write_text(json.dumps(regression,indent=2,sort_keys=True)+"\n")
if __name__=="__main__": main()
