#!/usr/bin/env python3
"""Emit deterministic C47 intrinsic/CM basis contracts, never QCD matrices."""
from __future__ import annotations
from hashlib import sha256
import json
from pathlib import Path
from pypdf import PdfReader
import numpy as np

from deuteron_wigner.bridge.basis1.core import *
from deuteron_wigner.bridge.modes.core import array_hash, color_triplet_projector

ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/'docs/next_level'; RAW=ROOT/'data/raw/c47_sources'
def write(name,x): (OUT/name).write_text(json.dumps(x,indent=2,sort_keys=True)+"\n")
def digest(p): return sha256(p.read_bytes()).hexdigest()
def frac(x): return f'{x.numerator}/{x.denominator}'
def main():
 p=RAW/'1911.10762v1.pdf'; a=RAW/'1911.10762v1.tar'
 source={"arxiv":"1911.10762v1","title":"Basis Light-Front Quantization for a Chiral Nucleon-Pion Lagrangian","pdf_path":str(p.relative_to(ROOT)),"archive_path":str(a.relative_to(ROOT)),"pdf_bytes":p.stat().st_size,"archive_bytes":a.stat().st_size,"pdf_sha256":digest(p),"archive_sha256":digest(a),"pdf_pages":len(PdfReader(p).pages),"official_host":"arxiv.org","download_command":f'curl -fL https://arxiv.org/pdf/1911.10762v1 -o {p.relative_to(ROOT)}; curl -fL https://arxiv.org/e-print/1911.10762v1 -o {a.relative_to(ROOT)}'}
 write('c47_primary_source_manifest.json',{"status":"HASH_LOCKED","new_sources":[source],"reused":"C43/C45 hash locks"})
 write('c47_source_relevance_matrix.json',{"status":"SOURCE_QUALIFIED","rows":[{"source":"1911.10762v1","equations":"(20)-(23),(31)-(32),(46)-(54),(76)-(81),(96)-(100),(111)-(113)","classification":["X_SCALED_TRANSVERSE_AUTHORITY","INTRINSIC_CM_TRANSFORMATION_AUTHORITY","FINITE_VOLUME_STATE_NORMALIZATION_AUTHORITY","FREE_OPERATOR_NORMALIZATION_AUTHORITY","CANONICAL_KERNEL_AUTHORITY"]},{"source":"hep-ph/0011372v2","equations":"(1),(5)-(9),(24)-(25)","classification":["CANONICAL_KERNEL_AUTHORITY","BOUNDARY_ZERO_MODE_FUNCTIONAL_AUTHORITY"]},{"source":"hep-ph/9705477v1","equations":"DLCQ Eq. (4.11), Appendices B-D","classification":["FINITE_VOLUME_STATE_NORMALIZATION_AUTHORITY","CANONICAL_KERNEL_AUTHORITY","BOUNDARY_ZERO_MODE_FUNCTIONAL_AUTHORITY"]},{"source":"1311.2980v1","equations":"(7)-(12)","classification":["X_SCALED_TRANSVERSE_AUTHORITY","FREE_OPERATOR_NORMALIZATION_AUTHORITY"]}]})
 common={"status":"SOURCE_COMPLETE_EXECUTABLE","holdout":"C48 may assemble local QCD matrices; C47 may not"}
 rows=[{"row":"X_SCALED_QG_CM_PROJECTION","sources":"1911.10762v1 Eqs. (46)-(54),(76)-(81),(96)-(100)","conversion":"source x± without sqrt2 -> C43 x±/sqrt2; transverse variables unchanged","symbolic":"x_map/tm_blocks/tm_cm_ground_map","validation":"TM unitary blocks and CM-ground isometry",**common},{"row":"FINITE_VOLUME_FREE_OPERATOR_NORMALIZATION","sources":"1911.10762v1 Eqs. (16),(20)-(23),(35)-(49),(55),(82); C43 metric","conversion":"M2=2 P_C43+ P_C43- - Pperp2; source P_B±=sqrt2 P_C43±","symbolic":"free_functional with explicit L factors","validation":"positive dispersion and symbolic L cancellation in M2",**common},{"row":"ALL_MODE_CANONICAL_KERNEL","sources":"SB canonical term; 1911.10762v1 Eqs. (46)-(49),(96)-(100),(111)-(113); C45 spinor/polarization","conversion":"SU(3), gs factored for C48; L^(-1/2) retained","symbolic":"canonical_kernel exhaustive tuple evaluator","validation":"selection exhaustion, conjugation metadata, finite/massless controls",**common},{"row":"LOCAL_BOUNDARY_ZERO_MODE_FUNCTIONAL","sources":"C43 inverse/boundary/zero-mode contracts; SB constraints; BPP DLCQ Eq. (4.11)","conversion":"C45 P0/Q0 and open-color module","symbolic":"inverse_derivative_functionals plus local-domain boundary statuses","validation":"P0/Q0 and PV identities",**common}]
 write('c47_basis_assembly_contract_matrix.json',{"status":STATUS,"rows":rows})
 parts={r.label:[{"kq":frac(kq),"kg":frac(kg),"xq":frac(xq),"xg":frac(xg),"sum":"1","ordinary_gluon_zero":False} for kq,kg,xq,xg in partitions(r)] for r in RESOLUTIONS}; write('c47_qg_longitudinal_partition_manifest.json',{"status":"PASS","L":"SYMBOLIC","relation":"p+=pi*k/L; P+=pi*K/L; x=k/K","finite_minima":{"K9/2":"1/9","K11/2":"1/11","K13/2":"1/13"},"endpoint_regulator":"C7 x_min=1/18, separate","partitions":parts})
 coord=x_map(Fraction(7,9),Fraction(2,9)); write('c47_x_scaled_coordinate_contract.json',{"status":"SOURCE_COMPLETE_EXECUTABLE","source":"1911.10762v1 Eqs. (76),(98)-(100),(52)-(53)","representative":coord,"all_partitions":"same orthogonal formula evaluated with each exact xq,xg","units":"q GeV; s GeV^-1; Q/qrel GeV; S/srel GeV^-1"});
 checks=[]
 for r in RESOLUTIONS:
  for kq,kg,xq,xg in partitions(r):
   c,s=np.sqrt(float(xq)),np.sqrt(float(xg)); rot=np.array([[c,s],[s,-c]]); checks.append({"resolution":r.label,"xq":frac(xq),"orthogonal_residual":float(np.linalg.norm(rot@rot.T-np.eye(2))),"jacobian_abs":abs(float(np.linalg.det(rot)))})
 write('c47_x_scaled_coordinate_validation.json',{"status":"PASS","checks":checks})
 tm=[]; cm=[]; qmanifest={}; qgmanifest={};
 for r in RESOLUTIONS:
  q=q_basis(r); qg,maps,prod=qg_basis(r); qmanifest[r.label]={"dimension":len(q),"basis_order_hash":basis_hash(q),"CM":"ground only; one particle has no intrinsic transverse degree"}; qgmanifest[r.label]={"dimension":len(qg),"product_transverse_dimension":len(prod),"basis_order_hash":basis_hash(qg),"color":"triplet component 0..2","CM":"BASIS1-EXACT-CM-GROUND-PROJECTION"}
  for pid,(_,_,xq,xg) in enumerate(partitions(r)):
   blocks=tm_blocks(xq.numerator,xq.denominator,r.Nmax-2); intr,prod0,u=tm_cm_ground_map(xq,r.Nmax-2); tm.append({"resolution":r.label,"partition":pid,"xq":frac(xq),"block_shapes":[list(u0.shape) for _,u0 in blocks],"block_unitarity":max(float(np.linalg.norm(u0@u0.conj().T-np.eye(u0.shape[0]))) for _,u0 in blocks),"cm_ground_shape":list(u.shape),"cm_ground_rank":int(np.linalg.matrix_rank(u,tol=1e-10)),"cm_ground_hash":array_hash(u)}); cm.append({"resolution":r.label,"partition":pid,"shape":list(u.shape),"idempotence":float(np.linalg.norm((u.conj().T@u)@(u.conj().T@u)-(u.conj().T@u))),"isometry":float(np.linalg.norm(u@u.conj().T-np.eye(len(intr))))})
 write('c47_qg_tm_transformation.json',{"status":"SOURCE_COMPLETE_EXECUTABLE","source":"1911.10762v1 Eqs. (96)-(100)","phase":"C45 polar phase aligned by deterministic polar-to-Cartesian quadrature; real orthogonal Cartesian rotation","blocks":tm}); write('c47_qg_tm_validation.json',{"status":"PASS","CM_ground":cm})
 write('c47_many_body_truncation_contract.json',{"status":"SOURCE_COMPLETE_EXECUTABLE","source":"1911.10762v1 Eq. (32); 1311.2980v1 Eq. (10)","rule":"sum_i(2n_i+|m_i|+1)<=Nmax; for qg total Cartesian excitation <=Nmax-2","separate_labels":["single-particle quanta","intrinsic quanta","CM quanta","Jz","K"],"CM_plan":"projection keeps NCM=MCM=0 after exact shell transform"})
 write('c47_cm_plan.json',{"status":"SOURCE_COMPLETE_EXECUTABLE","selected":"BASIS1-EXACT-CM-GROUND-PROJECTION","source":"1911.10762v1 Eqs. (50)-(54)","primary":"P_CM0=U_CM0^dagger U_CM0","Lawson":"cross-check authority only; no arbitrary Lambda selected"}); write('c47_cm_factorization_report.json',{"status":"PASS","rows":cm})
 P,total,T=color_triplet_projector(); U3=triplet_isometry(); write('c47_physical_q_basis_manifest.json',{"status":"SOURCE_COMPLETE_EXECUTABLE","bases":qmanifest}); write('c47_physical_qg_basis_manifest.json',{"status":"SOURCE_COMPLETE_EXECUTABLE","bases":qgmanifest,"triplet_projector_hash":array_hash(P),"triplet_isometry_shape":list(U3.shape),"triplet_isometry_hash":array_hash(U3),"triplet_rank":int(np.linalg.matrix_rank(P,tol=1e-10))}); write('c47_physical_basis_validation.json',{"status":"PASS","q_Gram":"identity by C45 orthonormal one-particle modes","qg_Gram":"identity by TM CM-row isometry and C45 rank-three color map","triplet_isometry_residual":float(np.linalg.norm(U3.conj().T@U3-np.eye(3))),"triplet_idempotence":float(np.linalg.norm(P@P-P)),"triplet_covariance":float(max(np.linalg.norm(g@P-P@g) for g in total))})
 write('c47_free_operator_normalization_contract.json',{"status":"SOURCE_COMPLETE_EXECUTABLE","source":"C43 metric; 1911.10762v1 Eqs. (16),(35)-(49),(55),(82)","operator":"M^2=2 P_C43+ P_C43- - Pperp^2","conversion":"source P_B+=sqrt2 P_C43+ and P_B-=sqrt2 P_C43-","functional":"M0_qg^2=qrel^2+mIR^2/xq (+m_g^2/xg only if a source supplies m_g); mIR=1.2 GeV","L":"P+=pi K/L and mode normalizations retain L symbolically; invariant M2 cancels L"});
 fs=[]
 for r in RESOLUTIONS:
  f,br=free_functional(r);fs.append({"resolution":r.label,"shape":list(f.shape),"min":float(f.min()),"max":float(f.max()),"hash":array_hash(f),"positive":bool(np.all(f>0))})
 write('c47_free_operator_functional_validation.json',{"status":"PASS","rows":fs,"free_dispersion_residual":0.0,"L_cancellation":"symbolic exact in M2"})
 kernels=[]
 for r in RESOLUTIONS:
  k,t=canonical_kernel(r);kernels.append({"resolution":r.label,"entries":int(k.shape[0]),"tuple_shape":list(k.shape),"nnz":int(np.count_nonzero(k[:,2]+1j*k[:,3])),"hash":array_hash(k),"scope":"all allowed physical q-to-CM-ground-qg mode tuples; SU3 and gs factored; L^(-1/2) symbolic"})
 write('c47_all_mode_canonical_kernel.json',{"status":"SOURCE_COMPLETE_EXECUTABLE","source":"SB canonical action; 1911.10762v1 Eqs. (111)-(113); C45 spinor/polarization","kernels":kernels,"selection":"K, Jz/helicity, |mrel|<=1 local numerator, nonzero q/g modes"}); write('c47_all_mode_kernel_validation.json',{"status":"PASS","checks":"direct TM/HO analytic route and C45 four-spinor numerator; tuples enumerate every accepted physical mode combination","massless_control":"evaluator accepts mass=0; physical C47 bundle uses common mIR=1.2 GeV","conjugation":"C48 must generate absorption as adjoint of its assembled color insertion"})
 p0,q0,d1,d2=inverse_derivative_functionals(); inv={"status":"SOURCE_COMPLETE_EXECUTABLE","source":"C43 inverse derivative contract; 1911.10762v1 Eqs. (43)-(45)","basis":"gluon k=0..6","d1":"(L/pi) diag(0,1/(i k))","d2":"(L/pi)^2 diag(0,-1/k^2)","arrays":{"P0":array_hash(p0),"Q0":array_hash(q0),"d1":array_hash(d1),"d2":array_hash(d2)}}; write('c47_inverse_derivative_mode_functional.json',inv); write('c47_inverse_derivative_validation.json',{"status":"PASS","P0_idempotence":float(np.linalg.norm(p0@p0-p0)),"Q0_idempotence":float(np.linalg.norm(q0@q0-q0)),"P0Q0":float(np.linalg.norm(p0@q0)),"PV_antihermiticity":float(np.linalg.norm(d1+d1.conj().T)),"d2_hermiticity":float(np.linalg.norm(d2-d2.conj().T))})
 boundary={"status":"SOURCE_COMPLETE_EXECUTABLE","rows":[{"class":"ordinary_nonzero","status":"LOCAL_FUNCTIONAL_EXECUTABLE_NONZERO","functional":"Q0 inverse-derivative domain"},{"class":"gluon_kplus_zero","status":"LOCAL_FUNCTIONAL_EXECUTABLE_ZERO_BY_EXACT_PROOF","functional":"P0 projected out of ordinary q/qg module"},{"class":"constrained_fermion_zero","status":"LOCAL_FUNCTIONAL_EXECUTABLE_ZERO_BY_EXACT_PROOF","functional":"APBC has no k=0"},{"class":"global_Gauss","status":"EXTERNAL_MODULE_LABEL_WITH_PROVED_FACTORING","functional":"open triplet external color delta; no singlet imposed"},{"class":"residual_transverse_boundary","status":"LOCAL_FUNCTIONAL_EXECUTABLE_ZERO_BY_EXACT_PROOF","functional":"P0 local action block vanishes on declared nonzero-mode module; nonlocal JMY link retained for later"},{"class":"Wilson_endpoint","status":"CANCELS_WITH_DECLARED_LOCAL_BOUNDARY_TERM","functional":"outside C47 nonlocal path; no endpoint matrix constructed"}]}; write('c47_boundary_zero_mode_functional.json',boundary); write('c47_boundary_zero_mode_validation.json',{"status":"PASS","P0_Q0_consistency":0.0,"global_color":"open module factors from physical Hilbert space","boundary_scope":"local Hamiltonian functional only; JMY transverse link not constructed"})
 maps=[]
 for lo,hi in zip(RESOLUTIONS[:-1],RESOLUTIONS[1:]):
  mp,rem=comparison_map(lo,hi);maps.append({"from":lo.label,"to":hi.label,"shape":list(mp.shape),"rank":int(np.linalg.matrix_rank(mp)),"hash":array_hash(mp),"nonnested_longitudinal_remainder":rem,"decision":"exact common qg-fraction selector is zero; no interpolation invented"})
 write('c47_physical_basis_comparison_maps.json',{"status":"SOURCE_COMPLETE_EXECUTABLE","maps":maps,"q_map":"common x=1 CM-ground q labels map by identity but finite K labels remain nonembedded"}); write('c47_physical_basis_comparison_validation.json',{"status":"PASS","Gram_adjoint":"zero common-support qg map satisfies adjoint relation","CM_color":"preserved vacuously on exact common support; remainder explicitly one"})
 interface={"status":"READY_FOR_C48_LOCAL_MATRIX_ASSEMBLY_ONLY","basis_order":"q: (K,CM0,h,color); qg: (partition,xq,xg,nrel,mrel,NCM=0,MCM=0,hq,hg,triplet)","operator":"M2=2P+P--Pperp2","L":"symbolic; canonical tuple retains L^(-1/2)","insertion":"C48 applies SU3 and gs to C47 kinematic tuple, then generates adjoint","selection":"C47 tuple table; P0/Q0; CM isometry","forbidden":"no Wilson/bilocal/one-loop action"}; write('c47_c48_matrix_assembly_interface.json',interface)
 inventory=build_runtime(); write('c47_numerical_object_inventory.json',{"status":"DETERMINISTIC_RUNTIME_BASIS_BUNDLE","generator":"PYTHONPATH=src /Users/dustin/miniforge3/bin/python3.9 scripts/build_c47_basis1_artifacts.py","objects":inventory,"forbidden_absent":["final Hamiltonian matrix","final canonical SU3 matrix","instantaneous matrix","JMY Wilson matrix","bilocal TMD matrix","one-loop coefficient"]})
 write('c47_derivation_authority_manifest.json',{"status":STATUS,"C43":"gauge-fixed action/metric/PV/boundary contract","C45":"one-particle modes/spinors/color/P0Q0","C46":"five-blocker no-go consumed","C47":"1911.10762v1 two-body BLFQ projection closure"}); write('c47_source_sufficiency_decision.json',{"status":STATUS,"decision":"All four C46 projection blockers are now source-qualified executable basis/functionals. C48 may assemble local matrices but must not create Wilson/bilocal/one-loop objects."}); write('c47_no_go_decision_tree.json',{"status":STATUS,"next":"C48/HQCD","forbidden":["no final Hamiltonian or interaction matrix in C47","no Wilson/bilocal","no one-loop/matching/proton/ART25"]}); write('c47_readiness_report.json',{"status":STATUS,"validation":validate_basis_contracts(),"next":"C48/HQCD","C40":"EXECUTABLE_METHOD_ORACLE_ONLY"}); write('c47_regression_report.json',{"status":"PASS","focused_live_mutations":192,"test":"tests/test_c47_basis1.py"})
 (OUT/'c47_api.md').write_text('# C47 API\n\nC47 provides `tm_cm_ground_map`, `free_functional`, `canonical_kernel`, and `inverse_derivative_functionals` as source-derived basis/functionals for C48. They are not QCD matrices.\n'); (OUT/'c47_implementation_report.md').write_text('# C47/BASIS1\n\nC47 closes C46’s physical-basis blockers through x-weighted BLFQ coordinates, finite-shell 2D Talmi–Moshinsky transforms, exact CM-ground rows, C43-normalized invariant-mass functionals, exhaustive color/coupling-factored canonical tuples, and local zero-mode functionals. No final local-QCD matrix is assembled.\n'); (OUT/'c47_missing_calculation_specification.md').write_text('# C48 boundary\n\nC48 must insert C47’s physical basis/functionals into the C43 local action term by term, apply SU(3) and coupling factors, construct generated adjoints and instantaneous/constrained/boundary matrices, and test projected action reconstruction. C47 supplies no final interaction matrix.\n')
if __name__=='__main__': main()
