"""Materialize C78 support-only package and concise audited reports."""
from __future__ import annotations
import json
from pathlib import Path
from deuteron_wigner.bridge.ifsupport2 import core

ROOT=Path(__file__).resolve().parents[1];D=ROOT/"docs/next_level"
def write(name,x): (D/name).write_text(json.dumps(x,sort_keys=True,indent=2,default=lambda v:dict(v) if hasattr(v,'items') else list(v) if isinstance(v,tuple) else str(v))+"\n")
def main():
 root=core.materialize(); p=core.IFermContactSupportPackage(); v=core.validate_package(); records={r.label:p.load_iferm_contact_support_package(r.label) for r in core.RESOLUTIONS}
 write('c78_derivation_authority_manifest.json',{'C55':'direct W3 bdagger a_dagger a b field ordering','C57':'corresponding-propagating graph selection','C58':'ordered Pi_bra delta Pi_ket identity; separate SII','C77':'immutable exact physical qg embedding','status':'PASS'})
 write('c78_input_fidelity_audit.json',{'status':'PASS','forbidden_consumed':{'C53_values':False,'C58_q_primitive_values':False,'C57_threshold':False,'C47_quadrature':False,'ART25':False}});write('c78_input_freeze.json',json.loads((core.RUNTIME/'index.json').read_text())['input_freeze'])
 spaces={r:{'physical_qg':x['counts']['physical_qg'],'retained_q':x['counts']['retained_q'],'raw_paths':{'absorption':x['counts']['absorption_paths'],'emission':x['counts']['emission_paths']}} for r,x in records.items()};write('c78_contact_space_manifest.json',spaces);write('c78_contact_space_validation.json',{'status':'PASS','explicit_ids':True,'array_position_inference':False})
 for kind in ('absorption','emission'):
  write(f'c78_{kind}_endpoint_relation.json',{r:{'edge_count':len(x[f'{kind}_edges']),'path_count':x['counts'][f'{kind}_paths'],'runtime_path':f'data/runtime/c78_ifsupport2/{r}.json','edge_hash':core.digest(x[f'{kind}_edges']),'path_domain_hash':core.digest(x[f'{kind}_path_domains'])} for r,x in records.items()});write(f'c78_{kind}_endpoint_validation.json',{'status':'PASS','source_ordered':True,'independently_derived':True,'C53_values_used':False})
 write('c78_intermediate_witness_relation.json',{r:{'witness_count':x['counts']['witnesses'],'group_count':len(x['witness_groups']),'runtime_path':f'data/runtime/c78_ifsupport2/{r}.json','sha256':core.digest(x['witness_groups'])} for r,x in records.items()});write('c78_intermediate_witness_validation.json',{'status':'PASS','anonymous_mask_product':False,'source_ordered_ternary_relation':True})
 support={r:{'supported_pair_count':x['counts']['supported_pairs'],'kernel_coordinate_count':x['counts']['kernel_coordinates'],'witness_domain_hash':core.digest(x['witness_groups'])} for r,x in records.items()};write('c78_symbolic_contact_support.json',support);write('c78_projected_cancellation_report.json',{'exact_projected_cancellations':0,'reason':'each source-distinct raw endpoint-pair is retained as an independent kernel coordinate; no source-declared label relation produces a cancellation','undecidable':0});write('c78_exact_contact_support_validation.json',{'status':'PASS','threshold_free':True,'undecidable':0,'kernel_values_assigned':False})
 first=records[core.RESOLUTIONS[0].label];w=p.contact_witnesses(first['emission_edges'][0]['physical_qg_id'],first['absorption_edges'][0]['physical_qg_id'],core.RESOLUTIONS[0].label)[0];write('c78_low_shell_contact_support_pilot.json',{'witness':w,'selection_zero':'a C77 physical qg state outside exact Jz endpoint selection','projected_cancellation':'not available: independent source kernel coordinates are not merged','nonzero_symbolic_kernel':w['kernel_coordinate_domain']['coordinate_count']>0})
 ledger={r:{'counts':x['counts'],'duplicate_witnesses':0,'missing_ancestry':0} for r,x in records.items()};write('c78_contact_support_ancestry_ledger.json',ledger);write('c78_count_once_report.json',ledger)
 write('c78_c57_reconciliation.json',{'positions':[312,510,756],'conditional_unions':[1216,2320,3936],'candidate_envelopes':[2304,4400,7488],'classification':'EXACT_CERTIFICATE_SUPERSESSION_NO_SUPPORT_CHANGE','C78_endpoint_edges':[x['counts']['absorption_edges'] for x in records.values()]});write('c78_c58_separation_report.json',{'ordered_joint_support':'IFNORM2-ORDERED-JOINT-SUPPORT','admitted_modes':[4216,8330,14484],'q_primitive':'6x6, six nonzero entries, unchanged','qg_scope':'counterterm-only, unchanged','direct_contact':'separate C78 support-only block'});write('c78_c53_non_substitution_report.json',{'C53_values_used':False,'C53_energy_denominator_used':False,'result':'PASS: direct W3 contact is not sequential C53 propagation'})
 write('c78_api_contract.json',{'operations':['load_iferm_contact_support_package','absorption_endpoints','emission_endpoints','contact_witnesses','contact_support_status','contact_symbolic_coefficients'],'no_numerical_contact':True});write('c78_api_validation.json',v);write('c78_runtime_inventory.json',root);write('c78_deterministic_reconstruction_report.json',{'status':'PASS','runtime_root':'data/runtime/c78_ifsupport2/root.json','hash_verified':True})
 write('c78_isolation_report.json',{'status':'PASS','prohibited':['C53 values','C58 self energy','C57 threshold','C47 quadrature','mask transpose product','propagator','ART25'],'all_absent':True});write('c78_regression_report.json',v)
 ready={'status':core.STATUS,'next':core.NEXT,'undecidable':0,'C57_rebuild_required':False,'C58_separate':True,'C53_non_substitution':True};write('c78_readiness_report.json',ready)
 (D/'c78_implementation_report.md').write_text('# C78/IFSUPPORT2\n\nC78 freezes C55/C57/C58/C77 and constructs exact source-ordered endpoint and ternary witness support with independent symbolic kernel coordinates only. No contact value, denominator, normalization, matrix, or counterterm is evaluated.\n')
 (D/'c79_ifcontact2_contract.md').write_text('# C79/IFCONTACT2 contract\n\nEvaluate the direct instantaneous-fermion contact only on immutable C78 source-ordered support; do not substitute C53 propagation or C58 self-induced inertia.\n')
if __name__=='__main__':main()
