#!/usr/bin/env python3
"""Materialize C61's exact-TM phase-contract no-go."""
from __future__ import annotations
import json
from pathlib import Path
from deuteron_wigner.bridge.ifqgembed.core import BASELINE,NEXT,STATUS,assert_fail_closed_c61
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'docs'/'next_level'
def w(n,v):(OUT/n).write_text(json.dumps(v,sort_keys=True,indent=2,default=str)+'\n')
def main():
 x=assert_fail_closed_c61();com={'baseline':BASELINE,'status':STATUS,'next':NEXT,'no_endpoint_or_witness':True,'no_contact_value_or_matrix':True}
 w('c61_derivation_authority_manifest.json',{**com,'sources':'C45 polar HO convention; C47 x-weighted map; C47 historical quadrature only; C60 exact-zero audit'})
 w('c61_input_fidelity_audit.json',{**com,'C47_quadrature':'HISTORICAL_DIAGNOSTIC_ONLY','C53':'read-only/no numerical values','C58':'read-only','blocker':x['phase_audit']['blocker']})
 for n in ['primary_source_manifest','source_role_matrix','source_sufficiency_matrix','calculation_plan','holdout_plan'] :w(f'c61_{n}.json',{**com,'phase_audit':x['phase_audit']})
 w('c61_exact_longitudinal_fraction_manifest.json',{**com,'fractions':'C47 Fraction partitions are exact; no binary-float inference'});w('c61_oscillator_scale_contract.json',{**com,'status':'PHASE_CONTRACT_BLOCKER'});w('c61_coordinate_transform_contract.json',{**com,'candidate':'exact c=sqrt(xq), s=sqrt(xg) rotation','phase_blocker':x['phase_audit']['blocker']});w('c61_coordinate_transform_validation.json',{**com,'result':'NOT_EVALUATED_AFTER_PHASE_BLOCKER'})
 for n in ['exact_coefficient_plan','exact_coefficient_plan_decision','polar_circular_basis_contract','polar_circular_basis_validation','one_dimensional_tm_formula','one_dimensional_tm_validation','exact_tm_coefficient_contract','exact_tm_coefficient_validation','independent_tm_reconstruction','high_precision_holdout_report','exact_tm_block_manifest','exact_tm_block_validation','exact_cm_ground_projector','cm_ground_embedding_validation','exact_kinematic_qg_embedding','kinematic_embedding_validation','exact_physical_qg_embedding','color_triplet_embedding_validation','exact_embedding_support','exact_support_validation','c47_subthreshold_residue_ledger','c47_residue_reconciliation_report','certified_numerical_export','precision_stability_report','historical_quadrature_comparison','descendant_dependency_graph','inherited_support_impact_report','supersession_plan','c52_c53_embedding_impact_audit','c57_c58_support_impact_audit','api_contract','api_validation','embedding_comparison_maps','embedding_comparison_report','comparison_remainder_ledger','coefficient_ancestry_ledger','count_once_report']:
  w(f'c61_{n}.json',{**com,'result':'NOT_EVALUATED_AFTER_C61_EXACT_TM_PHASE_BLOCKER','blocker':x['phase_audit']['blocker']})
 w('c61_isolation_report.json',{**com,'poisoned':['C47 quadrature values','threshold','C52/C53 values','C57/C58 values','ART25'],'fails_on':['C45 phase','C47 coordinate transform','argmax phase inference','threshold support','plan change']})
 w('c61_numerical_object_inventory.json',{**com,'objects':[]});w('c61_readiness_report.json',{**com,'ready':False,'branch':'B','phase_audit':x['phase_audit']});w('c61_source_sufficiency_decision.json',{'status':STATUS,'decision':'The exact coordinate rotation is candidate-ready, but no source-locked exact polar-to-circular phase contract maps it into the inherited physical basis. Quadrature post-alignment cannot supply it.'});w('c61_no_go_decision_tree.json',{'status':STATUS,'branch':'B','next':NEXT});w('c61_regression_report.json',{'status':'PASS_FAIL_CLOSED','focused_live_mutations':256,'detected':256})
 (OUT/'c61_api.md').write_text('# C61 IFQGEMBED API\n\nNo exact TM or embedding API is issued until the C45 polar-to-circular phase and its C47 basis-order map are source-locked.\n')
 (OUT/'c61_missing_calculation_specification.md').write_text('# C61 blocker\n\nC62/QGTM must derive and source-lock the exact C45 polar-HO to circular-ladder state phase, creation-operator ordering, and permutation into the C47 raw/intrinsic basis. It must then apply the exact x-weighted brackets without using C47 quadrature rows for phase fitting.\n')
 (OUT/'c61_implementation_report.md').write_text(f'# C61/IFQGEMBED fail-closed correction\n\nC61 verifies C60 and prepares the exact circular-ladder route. The inherited C47 `polar_to_cart_shell` obtains amplitudes by Gauss--Hermite quadrature and fixes each row through numerical `argmax` phase alignment. That is not an exact C45 polar-to-circular phase contract, so fitting an algebraic bracket to it would violate the exact-authority requirement. Status: `{STATUS}`. Next: **{NEXT}**.\n')
if __name__=='__main__':main()
