"""Two-dimensional symmetric-traceless tensors and rank projectors."""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np


def symmetric_traceless_2d(
    momentum: np.ndarray | tuple[float, float], rank: int
) -> np.ndarray:
    """Return the Cartesian rank-n STF tensor generated by ``momentum``.

    The normalization is the definite-rank convention used in
    arXiv:1612.06585: contraction with a transverse vector ``v`` gives

    ``STF_n(k):v^n = |k|^n |v|^n cos(n(phi_k-phi_v))/2^(n-1)``

    for ``rank >= 1``. Rank zero returns the scalar one.
    """

    vector = np.asarray(momentum, dtype=np.float64)
    if vector.shape != (2,):
        raise ValueError("transverse momentum must have shape (2,)")
    if rank < 0:
        raise ValueError("rank cannot be negative")
    if rank == 0:
        return np.asarray(1.0)
    z = complex(vector[0], vector[1]) ** rank
    tensor = np.empty((2,) * rank, dtype=np.float64)
    normalization = 2.0 ** (rank - 1)
    for indices in np.ndindex(tensor.shape):
        number_y = sum(indices)
        tensor[indices] = float((z * (-1j) ** number_y).real / normalization)
    return tensor


def contract_with_vector(tensor: np.ndarray, vector: np.ndarray) -> float:
    """Contract every tensor index with one copy of a two-vector."""

    array = np.asarray(tensor, dtype=np.float64)
    direction = np.asarray(vector, dtype=np.float64)
    if direction.shape != (2,):
        raise ValueError("contraction vector must have shape (2,)")
    if array.ndim == 0:
        return float(array)
    if array.shape != (2,) * array.ndim:
        raise ValueError("tensor must have dimension two on every index")
    result = array
    for _ in range(array.ndim):
        result = np.tensordot(result, direction, axes=(0, 0))
    return float(result)


@dataclass(frozen=True)
class DefiniteRankProjector:
    """Gram-normalized projector onto one Cartesian STF tensor."""

    basis: np.ndarray

    def __post_init__(self) -> None:
        array = np.asarray(self.basis, dtype=np.float64)
        if array.ndim == 0 or array.shape != (2,) * array.ndim:
            raise ValueError("projector basis must be a nonzero-rank 2D tensor")
        norm = float(np.vdot(array, array).real)
        if norm <= 0.0:
            raise ValueError("projector basis cannot vanish")
        object.__setattr__(self, "basis", array)

    @property
    def rank(self) -> int:
        return self.basis.ndim

    def coefficient(self, tensor: np.ndarray) -> float:
        values = np.asarray(tensor, dtype=np.float64)
        if values.shape != self.basis.shape:
            raise ValueError("tensor shape does not match projector basis")
        return float(
            np.vdot(self.basis, values).real
            / np.vdot(self.basis, self.basis).real
        )

    def reconstruct(self, coefficient: float) -> np.ndarray:
        return float(coefficient) * self.basis
